/**
 * @file render.js
 * @description Markdown renderings of an engagement document (ADR 0002).
 * GO → architecture.md, delivery-plan.md, capability-map.md, app-shortlist.md, risks.md.
 * STOP → stop-report.md. Larger Engagement (a STOP the consultant routed to a
 * Merkle Enterprise Engagement) → larger-engagement-brief.md and the four
 * approach artefacts.
 * Internal pricing and modifiers are never rendered.
 *
 * @module discovery/render
 */

import { stopRoute, needsApproach } from './engine.js';
import { countedIntegrations, distinctLanguages, marketsOf, hasChinaMainland } from './classify.js';
import { planSuggestion } from './plan.js';

const RESOLUTION_LABEL = { native: 'Native', app: 'App', theme: 'Theme', custom: 'Custom' };
const RESOLUTION_ORDER = ['native', 'app', 'theme', 'custom'];

/** Escape pipes and newlines so free text cannot break a Markdown table. */
const cell = (value) => String(value ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');

/**
 * @param {string[]} headers
 * @param {unknown[][]} rows
 */
function table(headers, rows) {
  if (rows.length === 0) return '_None._';
  return [
    `| ${headers.join(' | ')} |`,
    `|${headers.map(() => '---').join('|')}|`,
    ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`),
  ].join('\n');
}

/** "GO", "Larger Engagement", "STOP" or "STOP → No bid". @param {object} doc */
function statusLabel(doc) {
  if (doc.delivery.go) return 'GO';
  const route = stopRoute(doc);
  if (route?.brief) return route.label;
  return route ? `STOP → ${route.label}` : 'STOP';
}

/** @param {object} doc */
function header(doc, title) {
  const c = doc.meta.client;
  const route = stopRoute(doc);
  const offer = route && needsApproach(doc)
    ? `Nearest standard offer: ${doc.offer.code} — ${doc.offer.name} (${doc.offer.delivery_track}, reference only)`
    : `Offer: **${doc.offer.code} — ${doc.offer.name}** (${doc.offer.delivery_track})`;
  return [
    `# ${title} — ${c.name}`,
    '',
    `> Generated by the discovery engine from \`engagement.json\` · ${doc.meta.updated_at ?? doc.meta.created_at ?? ''}`,
    `> ${offer} · Status: **${statusLabel(doc)}**`,
    '> Edit `engagement.json`, not this file.',
    '',
  ].join('\n');
}

/** @param {object} doc */
function renderCapabilityMap(doc) {
  const rows = [...(doc.approach.capability_map ?? [])]
    .sort((a, b) => RESOLUTION_ORDER.indexOf(a.resolution) - RESOLUTION_ORDER.indexOf(b.resolution))
    .map((r) => [r.requirement, RESOLUTION_LABEL[r.resolution], r.tool, r.gaia_tier, r.notes, (r.question_ids ?? []).join(', '), links(r.sources)]);
  return `${header(doc, 'Capability Map')}
Resolution order: Native → App → Theme → Custom.

${table(['Requirement', 'Resolution', 'Tool / feature', 'Gaia tier', 'Notes', 'Questions', 'Sources'], rows)}
`;
}

/** Sources as Markdown links. @param {string[]|undefined} list */
const links = (list) => (list ?? []).map((url) => `[${url.replace(/^https:\/\/(www\.)?/, '')}](${url})`).join(' · ');
const label = (value) => String(value ?? '').replace(/_/g, ' ');

/** Sourced solution architecture (ADR 0017). @param {object} doc */
function renderArchitecture(doc) {
  const a = doc.approach.architecture ?? {};
  const decisions = (a.decisions ?? []).map((d) => `### ${d.topic}

**Question:** ${d.question ?? ''}

${table(['Option', 'Pros', 'Cons'], (d.options ?? []).map((o) => [o.option === d.decision ? `**${o.option}** (chosen)` : o.option, o.pros, o.cons]))}

**Decision:** ${d.decision} · plan impact: ${label(d.plan_impact)} · ${label(d.status)}

**Rationale:** ${d.rationale ?? ''}${d.question_ids?.length ? ` [${d.question_ids.join(', ')}]` : ''}

**Sources:** ${links(d.sources) || '_none_'}`).join('\n\n');
  return `${header(doc, 'Solution Architecture')}
Every Shopify statement cites an official source; client facts cite the discovery questions.

## Architecture decisions

${decisions || '_None drafted — run /architect._'}

## Integration architecture

${table(['System', 'System of record for', 'Pattern', 'Direction', 'Frequency', 'Shopify APIs', 'Error handling', 'Questions', 'Sources'],
    (a.integrations ?? []).map((i) => [i.system, (i.system_of_record_for ?? []).join(', '), label(i.pattern), label(i.direction), label(i.frequency), (i.shopify_apis ?? []).join(', '), i.error_handling, (i.question_ids ?? []).join(', '), links(i.sources)]))}

## Data model

${table(['Object', 'Kind', 'Name', 'Purpose', 'Source system', 'Sources'], (a.data_model ?? []).map((m) => [m.object, label(m.kind), m.name, m.purpose, m.source_system, links(m.sources)]))}

## Non-functional requirements

${table(['Area', 'Requirement', 'Approach', 'Sources'], (a.non_functional ?? []).map((n) => [label(n.area), n.requirement, n.approach, links(n.sources)]))}
`;
}

/** @param {object} app */
function cost(app) {
  if (!app.cost?.amount && app.cost?.amount !== 0) return app.cost?.note ?? '';
  const period = { month: '/mo', year: '/yr', one_off: ' one-off', usage: ' usage-based' }[app.cost.period] ?? '';
  return `${app.cost.currency ?? ''} ${app.cost.amount}${period}${app.cost.note ? ` (${app.cost.note})` : ''}`.trim();
}

/** @param {object} doc */
function renderAppShortlist(doc) {
  const apps = doc.approach.app_shortlist ?? [];
  const recommended = apps.filter((a) => a.recommended);
  const rejected = apps.filter((a) => !a.recommended);
  return `${header(doc, 'App Shortlist')}
## Recommended

${table(['App', 'Requirement', 'Why', 'Limitations', 'Cost', 'Integration', 'Gaia tier'],
    recommended.map((a) => [a.url ? `[${a.name}](${a.url})` : a.name, a.requirement, a.rationale, a.limitations, cost(a), a.integration_complexity, a.gaia_tier]))}

## Evaluated but not recommended

${table(['App', 'Reason'], rejected.map((a) => [a.name, a.rejection_reason]))}

> App costs are list prices at time of discovery — verify on the Shopify App Store.
`;
}

/** @param {object} doc */
function renderDeliveryPlan(doc) {
  const phases = (doc.approach.phases ?? []).map((phase) => {
    const sprints = phase.sprints.map((sprint) => `### ${sprint.name}

${table(['Task', 'Capability', 'Gaia tier', 'Owner', 'Deferred'],
      sprint.tasks.map((t) => [t.title, t.capability ? RESOLUTION_LABEL[t.capability] : '', t.gaia_tier, t.owner, t.deferred ? 'yes' : '']))}`).join('\n\n');
    return `## ${phase.name}\n\n${sprints}`;
  }).join('\n\n');

  const gates = Object.entries(doc.offer.scope_gates)
    .map(([id, g]) => [id.replace(/_/g, ' '), g.active ? 'active' : '—', g.evidence]);

  return `${header(doc, 'Delivery Plan')}
## Scope gates

${table(['Gate', 'Status', 'Evidence'], gates)}

${phases || '_No phases drafted._'}
`;
}

/** @param {object[]} items */
const exitRows = (items) => items.map((i) => [i.rule_id, i.result, i.evidence, i.destination, i.resolution?.owner ?? '', i.resolution?.status ?? '', i.source]);
const EXIT_HEADERS = ['Rule', 'Result', 'Evidence', 'Resolution path', 'Owner', 'Status', 'Source'];

/** @param {object} doc */
function notesSection(doc) {
  return `## Consultant notes

${table(['Date', 'Note'], (doc.notes ?? []).map((n) => [n.at ?? '', n.text]))}`;
}

/** @param {object} doc */
const openItemsTable = (doc) => table(['Question', 'Field', 'Why it matters'], (doc.approach?.risks?.open_items ?? []).map((o) => [o.question_id, o.pointer, o.why]));

/** @param {object} doc */
function renderRisks(doc) {
  const items = doc.exits.items;
  const risks = doc.approach.risks ?? {};
  return `${header(doc, 'Risks & Open Items')}
## Risk register

${table(['Risk', 'Likelihood', 'Impact', 'Mitigation', 'Owner', 'Evidence'], (risks.register ?? []).map((r) => [r.risk, r.likelihood, r.impact, r.mitigation, r.owner, (r.evidence ?? []).join(', ')]))}

## Hard blockers (STOP)

${table(EXIT_HEADERS, exitRows(items.filter((i) => i.result === 'STOP')))}

## Flags (need an owner before build)

${table(EXIT_HEADERS, exitRows(items.filter((i) => i.result === 'FLAG')))}

## Commercial warnings

${table(['Rule', 'Evidence', 'Action'], items.filter((i) => i.result === 'WARN').map((i) => [i.rule_id, i.evidence, i.destination]))}

## Open items (unanswered questions)

${table(['Question', 'Field', 'Why it matters'], (risks.open_items ?? []).map((o) => [o.question_id, o.pointer, o.why]))}

## Assumptions

${table(['Assumption', 'Impact if wrong'], (risks.assumptions ?? []).map((a) => [a.statement, a.impact_if_wrong]))}

${notesSection(doc)}
`;
}

/** @param {object} doc */
function renderStopReport(doc) {
  const stops = doc.exits.items.filter((i) => i.result === 'STOP' && i.resolution?.status === 'open');
  const route = stopRoute(doc);
  let intro = `Discovery cannot close: ${stops.length} hard blocker(s) are open. No delivery plan, capability map
or app shortlist was generated. Resolve or waive each blocker in \`engagement.json\` and re-run, or record
how Merkle proceeds (\`delivery.route\`, question Q10.5.5): Larger Engagement or no bid.`;
  if (route) {
    intro = `Discovery hit ${stops.length} hard blocker(s). Decision: **${route.label}** — ${route.description}`;
  }
  return `${header(doc, 'STOP Report')}
${intro}

## Open hard blockers

${table(EXIT_HEADERS, exitRows(stops))}

## Other exit results

${table(EXIT_HEADERS, exitRows(doc.exits.items.filter((i) => !stops.includes(i))))}

## Open items (unanswered questions)

${openItemsTable(doc)}

${notesSection(doc)}
`;
}

// ─── Larger Engagement brief ──────────────────────────────────────────────────

/** @param {unknown} v */
const yesNo = (v) => (v === true ? 'yes' : v === false ? 'no' : 'not answered');
/** @param {unknown} v @param {string} [fallback] */
const orNa = (v, fallback = 'not answered') => (v === undefined || v === null || v === '' || (Array.isArray(v) && v.length === 0) ? fallback : Array.isArray(v) ? v.join(', ') : String(v));
/** @param {string|undefined} v */
const human = (v) => (v ? String(v).replace(/_/g, ' ') : v);

/** China discovery inputs (§ 3.5) as a table. @param {object} doc */
function chinaTable(doc) {
  const c = doc.china ?? {};
  const v = (x) => (x === undefined ? 'not answered' : Array.isArray(x) ? x.map(human).join(', ') || 'not answered' : typeof x === 'boolean' ? yesNo(x) : human(String(x)));
  return table(['Topic', 'Answer'], [
    ['Selling model', v(c.selling_model)], ['Channels', v(c.channels)], ['PRC entity', v(c.prc_entity)],
    ['Overseas entity / trademarks in China', `${v(c.overseas_entity)} / ${v(c.trademarks_registered_in_china)}`],
    ['ICP', v(c.icp_status)], ['Shopify role', v(c.shopify_role)], ['Customs modes', v(c.customs_modes)],
    ['Positive list', v(c.positive_list)], ['Product classes', v(c.product_classes)], ['NMPA', v(c.nmpa_status)],
    ['Claims review', v(c.claims_review_needed)], ['Payments', v(c.payments)], ['Customers per year', v(c.customers_per_year)],
    ['PIPL representative', v(c.pipl_representative)], ['Customer data location', v(c.customer_data_location)],
    ['Blocked services review', v(c.blocked_services_review)], ['Marketing channels', v(c.marketing_channels)],
    ['Customer service', v(c.customer_service)], ['Local partner', v(c.local_partner)], ['China launch target', v(c.target_launch_date)],
    ['PRC legal, tax and customs advice', v(c.legal_advice)],
  ]) + '\n\nReference: `discovery/docs/china-mainland.md`.';
}

/** Scope profile rows: what makes this engagement bigger than an offer. @param {object} doc */
function scopeRows(doc) {
  const markets = marketsOf(doc);
  const b2b = doc.b2b ?? {};
  const cat = doc.catalogue ?? {};
  const plan = planSuggestion(doc);
  const counted = countedIntegrations(doc);
  const figma = doc.design?.figma ?? {};
  const comp = doc.compliance ?? {};
  const b2bDetail = b2b.enabled
    ? [b2b.company_accounts && 'company accounts', b2b.price_lists && 'company price lists', b2b.volume_discounts && 'volume discounts', b2b.rfq_or_negotiated_pricing && 'quotes / negotiated pricing'].filter(Boolean).join(', ')
    : '';
  return [
    ['Markets at launch', `${markets.length}: ${markets.map((m) => `${m.code} (${m.currency ?? '?'}${m.price_strategy ? `, ${human(m.price_strategy)}` : ''})`).join(', ') || 'not answered'}`],
    ...(hasChinaMainland(doc) ? [['Mainland China', 'Launch market excluded from this engagement — separate China discovery (Great Firewall: ICP licence, onshore hosting; 11.20)']] : []),
    ['Primary markets', orNa(doc.markets?.primary_markets)],
    ['Languages', `${distinctLanguages(doc).length}: ${distinctLanguages(doc).join(', ') || 'not answered'}`],
    ['B2B', b2b.enabled === undefined ? 'not answered' : b2b.enabled ? `yes — ${b2bDetail || 'details not answered'}` : 'no'],
    ['Catalogue', `${orNa(cat.sku_count)} SKUs · up to ${orNa(cat.variant_options_max)} variant options · ${orNa((cat.product_types ?? []).map(human))}`],
    ['Checkout', orNa(human(doc.checkout?.customisation))],
    ['Payments', orNa(doc.payments?.providers)],
    ['Fulfilment', `${orNa(doc.shipping?.fulfilment_locations)} location(s) · ${orNa(human(doc.shipping?.model))}`],
    ['Orders per month (year one)', orNa(doc.post_purchase?.orders_per_month)],
    ['Integrations', `${(doc.integrations ?? []).length} systems, ${counted.length} counted (ERP, PIM, CRM, WMS/3PL, OMS, custom)`],
    ['Migration', doc.migration?.source_platform ? `from ${doc.migration.source_platform}${doc.migration.seo_equity ? ` · SEO equity ${doc.migration.seo_equity}` : ''}` : 'not answered'],
    ['Storefront', `${doc.offer.delivery_track === 'hydrogen' ? 'headless (Hydrogen)' : 'Horizon theme'} · headless required: ${yesNo(doc.design?.headless_required)}`],
    ['Design', `Figma: ${yesNo(figma.exists)}${figma.completeness ? ` (${human(figma.completeness)})` : ''} · design system: ${yesNo(figma.design_system)} · accessibility: ${orNa(human(doc.design?.accessibility?.target))}`],
    ['Compliance', `privacy: ${orNa(comp.privacy_regimes)} · sensitive data: ${yesNo(comp.sensitive_data)} · regulated: ${comp.regulated_industry?.active ? (comp.regulated_industry.category ?? 'yes') : yesNo(comp.regulated_industry?.active)} · export/deletion workflow: ${yesNo(comp.gdpr_deletion_workflow)}`],
    ['Shopify plan', doc.shopify?.target_plan ? human(doc.shopify.target_plan) : plan ? `not decided — minimum ${plan.value}: ${plan.reasons.join('; ')}` : 'not decided — no feature above Basic identified'],
    ['Target go-live', orNa(doc.delivery?.target_launch_date)],
  ];
}

/** @param {object} doc */
function renderBrief(doc) {
  const route = stopRoute(doc);
  const c = doc.meta.client;
  const b = doc.business ?? {};
  const stops = doc.exits.items.filter((i) => i.result === 'STOP' && i.resolution?.status === 'open');
  const flags = doc.exits.items.filter((i) => i.result === 'FLAG');
  const approach = doc.approach ?? {};
  const byResolution = Object.fromEntries(RESOLUTION_ORDER.map((r) => [r, (approach.capability_map ?? []).filter((x) => x.resolution === r).length]));
  const sprints = (approach.phases ?? []).reduce((n, p) => n + p.sprints.length, 0);
  const active = (entries) => Object.entries(entries ?? {}).filter(([, g]) => g.active).map(([id]) => human(id));
  const d = doc.delivery ?? {};

  return `${header(doc, `${route.label} Brief`)}
${route.description}

This brief collects everything discovery found so the consultant can shape the ${route.proposal}. It contains no
Merkle pricing; the nearest standard offer is for reference only. Client deck: \`/deck ${c.slug}\`.

## Why this is a Larger Engagement

${table(['Rule', 'Blocker', 'Evidence', 'Workstream'], stops.map((i) => [i.rule_id, i.detail, i.evidence, i.destination]))}

## Client and objectives

${table(['Topic', 'Answer'], [
    ['Client', `${c.legal_name ?? c.name}${c.hq_country ? ` · HQ ${c.hq_country}` : ''}`],
    ['Industry', orNa(c.industry)],
    ['Business model', orNa(human(c.business_model))],
    ['Brand positioning', orNa(human(doc.brand?.positioning))],
    ['Core problem', orNa(b.primary_problem)],
    ['Growth goals', orNa(b.growth_goals)],
    ['KPIs', orNa((b.kpis ?? []).map((k) => `${k.metric}: ${k.baseline ?? '?'} → ${k.target ?? '?'}${k.horizon_months ? ` in ${k.horizon_months} months` : ''}`))],
    ['Client budget', b.budget ? `${b.budget.currency ?? ''} ${b.budget.min ?? '?'}–${b.budget.max ?? '?'}`.trim() : 'not answered'],
  ])}

## Scope profile

${table(['Area', 'Discovery answer'], scopeRows(doc))}

${hasChinaMainland(doc) ? `## Mainland China (separate China discovery, outside this engagement)

${chinaTable(doc)}

` : ''}## Integration landscape

${table(['System', 'Category', 'Direction', 'Data', 'Connector', 'Status'], (doc.integrations ?? []).map((i) => [i.system, i.category, i.direction ?? '', (i.objects ?? []).join(', '), [i.connector, i.middleware].filter(Boolean).join(' via '), human(i.status) ?? '']))}

## Governance

${table(['Role', 'RACI', 'Decision-maker'], (doc.stakeholders ?? []).map((s) => [s.role, s.raci ?? '', s.decision_maker ? 'yes' : '']))}

Single decision-maker: ${yesNo(d.decision_maker_confirmed)} · budget authority clear: ${yesNo(d.budget_authority_clear)}

## Flags to resolve before build

${table(['Rule', 'Evidence', 'Resolution path', 'Owner'], flags.map((i) => [i.rule_id, i.evidence, i.destination, i.resolution?.owner ?? '']))}

## Nearest standard offer (reference only)

${doc.offer.code} — ${doc.offer.name} · track ${doc.offer.delivery_track} · active scope gates: ${orNa(active(doc.offer.scope_gates), 'none')} · L triggers: ${orNa(active(doc.offer.l_triggers), 'none')}

## Drafted approach (starting point for the Discovery Phase)

${(approach.capability_map ?? []).length} requirements mapped (native ${byResolution.native}, app ${byResolution.app}, theme ${byResolution.theme}, custom ${byResolution.custom}) ·
${(approach.app_shortlist ?? []).filter((a) => a.recommended).length} apps recommended · ${(approach.phases ?? []).length} phase(s), ${sprints} sprint(s).
Details: \`architecture.md\`, \`capability-map.md\`, \`app-shortlist.md\`, \`delivery-plan.md\`, \`risks.md\`. No Jira tickets: the backlog is
defined in the dedicated Discovery Phase.

## Open items

${openItemsTable(doc)}

${notesSection(doc)}
`;
}

/**
 * Render the Markdown artefacts for an engagement.
 *
 * @param {object} doc  Schema-valid engagement document
 * @returns {Record<string, string>}  filename → content
 */
export function renderArtefacts(doc) {
  const route = stopRoute(doc);
  if (!doc.delivery.go && !(route?.brief && needsApproach(doc))) return { 'stop-report.md': renderStopReport(doc) };
  return {
    ...(route?.brief ? { [route.brief]: renderBrief(doc) } : {}),
    'architecture.md': renderArchitecture(doc),
    'delivery-plan.md': renderDeliveryPlan(doc),
    'capability-map.md': renderCapabilityMap(doc),
    'app-shortlist.md': renderAppShortlist(doc),
    'risks.md': renderRisks(doc),
  };
}
