/**
 * @file promotions.js — epic "Promotions & loyalty" (LWC-PRM-*)
 */

import { list, listOr, markets, isB2b, themeName } from './helpers.js';

const types = (doc) => doc.promotions?.discount_types ?? [];
const stackingText = {
  none: 'discounts never combine',
  native_combinations: 'product, order and shipping discounts combine natively (up to 5 codes plus 1 shipping code, up to 25 automatic discounts)',
  multiple_discounts_same_item: 'several product discounts combine on the same item (Shopify Plus)',
  custom_logic_function: 'custom stacking logic beyond native combinations (delivered by a discount function)',
};
const loyaltyInScope = (doc) => ['launch', 'phase_2'].includes(doc.loyalty?.phase) && (doc.loyalty?.components?.length ?? 0) > 0;

/** @type {import('../model.js').StoryDefinition[]} */
export default [
  {
    key: 'LWC-PRM-001',
    epic: 'promotions',
    title: 'Set up discount types and combination rules',
    description: (doc) => `Discount types: ${list(types(doc).map((t) => t.replace(/_/g, ' ')))}. Stacking: ${stackingText[doc.promotions?.stacking] ?? 'to confirm'}.`,
    user_story: 'As a marketer, I want to run the promotion types we rely on without developer help, so that campaigns launch on time.',
    acceptance_criteria: (doc) => [
      ...types(doc).filter((t) => !['scheduled_sale', 'stackable', 'automatic', 'code_based'].includes(t)).map((t) => `Given a ${t.replace(/_/g, ' ')} discount template, when a marketer creates one in the admin, then it applies to eligible items and markets in cart and checkout with the correct amount`),
      'Given any new discount, when it is saved, then its eligibility, usage limits, markets and dates are recorded in the promotions log',
      `Given the stacking rule (${stackingText[doc.promotions?.stacking] ?? 'to confirm'}), when a shopper applies several discounts, then only the allowed combinations apply and the best eligible outcome is shown`,
      ...(doc.promotions?.campaigns?.market_specific ? [`Given a market-specific promotion, when it is limited to ${listOr(markets(doc).map((m) => m.code), 'one market')}, then shoppers in other markets cannot use it`] : []),
      ...(isB2b(doc) ? ['Given a B2B buyer, when retail discounts are active, then they do not apply to B2B catalog prices unless explicitly allowed'] : []),
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'agent',
    depends_on: ['LWC-PAY-002'],
    spec_refs: ['/promotions/discount_types', '/promotions/stacking', '/promotions/campaigns/market_specific'],
    applies: (doc) => types(doc).length > 0,
    agent_prompt: (doc) => `Discount types: ${list(types(doc))}. Stacking: ${stackingText[doc.promotions?.stacking] ?? 'to confirm'}. Use native Shopify discounts (amount off products, amount off order, buy X get Y, free shipping; automatic or code) with combination settings per discount class. ${types(doc).includes('volume_tiered') && !isB2b(doc) ? 'Tiered volume discounts for retail may need a discount function — flag it before building. ' : ''}${types(doc).includes('pos_only') ? 'POS-only discounts: restrict eligibility to the Point of Sale channel. ' : ''}Restrict by market where required. Create one example of each type on the build store, document the recipe for marketers and test combinations in cart and checkout.`,
  },
  {
    key: 'LWC-PRM-002',
    epic: 'promotions',
    title: (doc) => (doc.promotions?.stacking === 'custom_logic_function' ? 'Build a discount function for advanced stacking rules' : 'Build a discount function for tiered discounts'),
    user_story: 'As a marketer, I want promotions to stack according to our rules, so that offers work as advertised without margin leaks.',
    acceptance_criteria: [
      'Given the documented stacking rules, when the discount function runs, then every rule has unit tests with passing and failing cart fixtures',
      'Given native discount combinations, when they already express a rule, then that rule is configured natively and not in the function',
      'Given the function configuration, when a marketer changes thresholds or percentages, then they do so through metafields on the discount without a code deploy',
    ],
    gaia_tier: 'T3',
    points: 8,
    owner: 'developer',
    depends_on: ['LWC-PRM-001', 'LWC-FND-002'],
    spec_refs: ['/promotions/stacking', '/promotions/discount_types'],
    security_flags: ['secrets'],
    gates: ['custom_promotions'],
    applies: (doc) => doc.offer?.scope_gates?.custom_promotions?.active === true,
    agent_prompt: (doc) => `Write down every stacking rule for ${list(types(doc))} and mark which native combinations already cover. For the remainder, scaffold a Discount Function (Shopify Functions discount API, latest stable version) with Shopify CLI — in the store's custom app on Shopify Plus, or delivered through a public App Store app below Plus, since only Plus stores can run custom apps that contain Functions — read configuration from the discount's metafield, add input-query fixtures and unit tests, and expose a simple admin UI extension or metafield editor for marketers. Deploy to the build store only after consultant review of the rule table.`,
  },
  {
    key: 'LWC-PRM-003',
    epic: 'promotions',
    title: (doc) => `Generate ${doc.promotions?.coupons?.branded ? 'branded and ' : ''}bulk coupon codes`,
    user_story: 'As a marketer, I want unique and branded codes for partners and emails, so that I can track and limit each campaign.',
    acceptance_criteria: (doc) => [
      'Given a campaign needing unique codes, when codes are generated, then each is single-use, tied to one discount and exportable for the distribution channel',
      ...(doc.promotions?.coupons?.branded ? ['Given a branded code for an influencer or partner, when it is created, then it is human-readable, usage-limited and reported separately'] : []),
      `Given code expiry "${doc.promotions?.coupons?.expiry ?? 'none'}", when a code is past its end, then checkout rejects it with a clear message`,
      `Given the distribution channels ${listOr(doc.promotions?.coupons?.distribution, 'agreed')}, when codes are delivered, then no code list is shared in plain email or public documents`,
    ],
    gaia_tier: 'T2',
    points: 2,
    owner: 'agent',
    depends_on: ['LWC-PRM-001'],
    spec_refs: ['/promotions/coupons/usage', '/promotions/coupons/branded', '/promotions/coupons/expiry', '/promotions/coupons/distribution', '/marketing/esp/platform'],
    applies: (doc) => (doc.promotions?.coupons?.usage ?? []).includes('bulk') || doc.promotions?.coupons?.branded === true,
    agent_prompt: (doc) => `Set up coupon codes: usage ${listOr(doc.promotions?.coupons?.usage, 'to confirm')}, expiry ${doc.promotions?.coupons?.expiry ?? 'none'}, distribution ${listOr(doc.promotions?.coupons?.distribution, 'to confirm')}. For bulk unique codes use discountRedeemCodeBulkAdd via the Admin API${doc.marketing?.esp?.platform ? ` or ${doc.marketing.esp.platform}'s unique coupon feature for email` : ''}. Create branded codes per partner with usage limits. Share code files only through the client's secure storage. Document the recipe.`,
  },
  {
    key: 'LWC-PRM-004',
    epic: 'promotions',
    title: 'Schedule sales that start and end automatically',
    user_story: 'As a marketer, I want sales to go live and end on time without anyone awake at midnight, so that campaigns are reliable.',
    acceptance_criteria: (doc) => [
      'Given a scheduled sale, when its start time arrives in the store time zone, then discounts, sale prices and storefront banners switch on together',
      'Given the end time, when it passes, then prices and banners revert and no sale price remains on any product',
      ...(doc.promotions?.campaigns?.market_specific ? ['Given a market-specific sale, when it runs, then only that market\'s prices or discounts change'] : []),
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'agent',
    depends_on: ['LWC-PRM-001'],
    spec_refs: ['/promotions/discount_types', '/promotions/campaigns/market_specific'],
    applies: (doc) => types(doc).includes('scheduled_sale'),
    agent_prompt: (doc) => `Prefer automatic discounts with start and end dates for sales (prices stay intact). Where compare-at price changes are required, build a Shopify Flow workflow with a scheduled trigger that sets and reverts compare-at and sale prices for a tagged collection, with a dry-run report first. Schedule storefront banners in ${themeName(doc)} with theme settings or a metaobject that has start and end dates. Test a sale starting and ending within one hour on the build store.`,
  },
  {
    key: 'LWC-PRM-005',
    epic: 'promotions',
    title: (doc) => `Launch the loyalty programme with ${doc.loyalty?.app ?? 'the selected loyalty app'}`,
    user_story: 'As a loyal customer, I want to earn and redeem rewards, so that buying again feels worthwhile.',
    description: (doc) => `Components: ${list((doc.loyalty?.components ?? []).map((c) => c.replace(/_/g, ' ')))}. Phase: ${doc.loyalty?.phase === 'phase_2' ? 'after launch' : 'launch'}.`,
    acceptance_criteria: (doc) => [
      ...(doc.loyalty?.components ?? []).map((c) => `Given the ${c.replace(/_/g, ' ')} component, when a test customer completes the qualifying action, then the reward is issued and visible in the loyalty widget and customer account`),
      ...(doc.loyalty?.esp_sync ? [`Given loyalty events, when points or tiers change, then ${doc.marketing?.esp?.platform ?? 'the ESP'} receives the profile properties for flows`] : []),
      'Given the loyalty programme terms, when they are published, then they are translated and linked from the footer',
    ],
    gaia_tier: 'T2',
    points: 5,
    owner: 'agent',
    depends_on: ['LWC-CUS-001', 'LWC-THM-001'],
    spec_refs: ['/loyalty/components', '/loyalty/phase', '/loyalty/app', '/loyalty/esp_sync'],
    security_flags: ['pii'],
    deferred: (doc) => doc.loyalty?.phase === 'phase_2',
    applies: loyaltyInScope,
    agent_prompt: (doc) => `Install ${doc.loyalty?.app ?? 'the approved loyalty app'} (check the plan fits the monthly app budget). Configure components: ${list((doc.loyalty?.components ?? []).map((c) => c.replace(/_/g, ' ')))}. Add the app's theme app extension blocks (launcher, points on product page, account panel) through the theme editor — no code snippets pasted into Liquid. ${doc.loyalty?.esp_sync ? `Connect the loyalty app to ${doc.marketing?.esp?.platform ?? 'the ESP'} for loyalty flows. ` : ''}Translate all loyalty texts. ${doc.loyalty?.phase === 'phase_2' ? 'This story is phase 2: do not install during the launch build; re-confirm scope and budget first.' : ''}`,
  },
  {
    key: 'LWC-PRM-006',
    epic: 'promotions',
    title: (doc) => `Set up affiliate and creator tracking${doc.marketing?.affiliate?.shopify_collabs ? ' with Shopify Collabs' : ''}${doc.marketing?.affiliate?.platform ? ` and ${doc.marketing.affiliate.platform}` : ''}`,
    user_story: 'As a marketer, I want to track sales from creators and affiliates, so that partners are paid fairly for results.',
    acceptance_criteria: (doc) => [
      `Given tracking method "${doc.marketing?.affiliate?.tracking ?? 'to confirm'}", when a test order uses an affiliate link or code, then the sale is attributed to the right partner`,
      'Given commissions, when an attributed order is refunded, then the commission is reversed',
      'Given affiliate scripts, when they load, then they respect cookie consent and add no blocking script to the storefront',
    ],
    gaia_tier: 'T2',
    points: 2,
    owner: 'agent',
    depends_on: ['LWC-PRM-001'],
    spec_refs: ['/marketing/affiliate/platform', '/marketing/affiliate/shopify_collabs', '/marketing/affiliate/tracking'],
    applies: (doc) => Boolean(doc.marketing?.affiliate?.platform) || doc.marketing?.affiliate?.shopify_collabs === true,
    agent_prompt: (doc) => `Configure ${[doc.marketing?.affiliate?.shopify_collabs ? 'Shopify Collabs' : '', doc.marketing?.affiliate?.platform ?? ''].filter(Boolean).join(' and ')} for affiliate tracking (${doc.marketing?.affiliate?.tracking ?? 'method to confirm'}): commission rules, partner discount codes and links, payout method and refund handling. Load any tracking via the app's web pixel or theme app extension so consent is respected. Place a test attributed order and a refund.`,
  },
  {
    key: 'LWC-PRM-007',
    epic: 'promotions',
    title: 'Build campaign landing pages and a countdown block',
    user_story: 'As a marketer, I want to build campaign pages and honest countdowns myself, so that campaigns launch fast and stay on brand.',
    acceptance_criteria: (doc) => [
      ...(doc.promotions?.campaigns?.landing_pages ? ['Given a campaign, when a marketer creates a landing page from the campaign template, then hero, product grid, countdown and FAQ blocks are available in the theme editor'] : []),
      ...(doc.promotions?.campaigns?.countdown_timer ? ['Given a countdown block, when its end date passes, then it hides automatically and it never resets for returning visitors (no fake urgency)'] : []),
      'Given a campaign page, when it is audited, then it meets the performance and accessibility budgets of the product pages',
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'developer',
    depends_on: ['LWC-THM-003'],
    spec_refs: ['/promotions/campaigns/landing_pages', '/promotions/campaigns/countdown_timer', '/promotions/campaigns/market_specific'],
    applies: (doc) => doc.promotions?.campaigns?.landing_pages === true || doc.promotions?.campaigns?.countdown_timer === true,
    agent_prompt: (doc) => `${doc.promotions?.campaigns?.landing_pages ? `Create a campaign page template in ${themeName(doc)} composed of existing sections and theme blocks. ` : ''}${doc.promotions?.campaigns?.countdown_timer ? 'Build a countdown theme block with an end-date setting, server-rendered fallback text, a small deferred web component and aria-live off (announce only the end state). It must hide after the end date and never restart per visitor. ' : ''}${doc.promotions?.campaigns?.market_specific ? 'Allow the block or page to be shown only in selected markets using localization.market conditions. ' : ''}Validate with Theme Check.`,
  },
];
