/**
 * @file theme.js — epic "Storefront & theme" (LWC-THM-*)
 *
 * Liquid track only (Online Store 2.0). Hydrogen storefront stories are not
 * part of this catalogue yet.
 */

import { isLiquidTrack, themeName, list, listOr, markets, languages, gate, isB2b, storeName } from './helpers.js';

const patterns = (doc) => doc.design?.interactive_patterns ?? [];
const hasPattern = (doc, re) => patterns(doc).some((p) => re.test(p));

/** @type {import('../model.js').StoryDefinition[]} */
export default [
  {
    key: 'LWC-THM-001',
    epic: 'theme',
    title: (doc) => `Install ${themeName(doc)} and apply brand tokens through theme settings`,
    user_story: 'As a shopper, I want the store to look unmistakably like the brand, so that I trust it from the first page.',
    description: (doc) => `Aesthetic: ${doc.design?.aesthetic ?? 'to be defined with the client'}. Brand guidelines: ${doc.brand?.has_guidelines ? 'available' : 'not available'}. Figma: ${doc.design?.figma?.completeness ?? 'none'}.`,
    acceptance_criteria: [
      'Given the brand guidelines, when colour schemes are configured in the theme editor, then every scheme meets WCAG AA contrast for text and buttons',
      'Given the brand typography, when fonts are selected, then they come from the Shopify font library or are uploaded as theme assets with font-display swap',
      'Given the theme code, when it is searched for hex colours, font names and pixel radii outside settings, then no hard-coded brand values are found',
      'Given the logo and favicon, when the storefront is loaded on mobile and desktop, then they render crisply from theme settings with correct alt text',
    ],
    gaia_tier: 'T2',
    points: 5,
    owner: 'developer',
    depends_on: ['LWC-FND-002'],
    spec_refs: ['/design/theme_preference', '/design/aesthetic', '/brand/has_guidelines', '/brand/asset_formats', '/design/figma/completeness'],
    applies: (doc) => isLiquidTrack(doc),
    agent_prompt: (doc) => `Install the latest ${themeName(doc)} release on the build store as an unpublished theme. Translate the brand guidelines into theme settings only: colour schemes (background, foreground, primary and secondary buttons, borders) in config/settings_data.json via the theme editor, heading and body fonts, type scale, button and card corner radius, spacing and logo/favicon. Aesthetic direction: ${doc.design?.aesthetic ?? 'confirm with the designer'}. Do not add hex values, font names or radii to Liquid, CSS or blocks — reference settings and CSS custom properties generated by the theme. Check contrast for every colour scheme and present a before/after preview for designer approval.`,
  },
  {
    key: 'LWC-THM-002',
    epic: 'theme',
    title: (doc) => `Build header, ${hasPattern(doc, /mega/i) ? 'mega-menu' : 'navigation'} and footer${gate(doc, 'markets') || languages(doc).length > 1 ? ' with country and language selectors' : ''}`,
    user_story: 'As a shopper, I want to find categories quickly and switch country or language easily, so that I reach the right products without friction.',
    acceptance_criteria: (doc) => [
      `Given the main menu, when it is opened on desktop and mobile, then ${hasPattern(doc, /mega/i) ? 'the mega-menu shows category columns and a promotional image block' : 'every top category is reachable in two taps or fewer'} and is fully keyboard operable`,
      ...(gate(doc, 'markets') || languages(doc).length > 1
        ? [`Given the header or footer, when a shopper opens the country/language selector, then it lists ${listOr(markets(doc).map((m) => m.code), 'every market')} and ${listOr(languages(doc), 'every published language')} using Shopify's localization form`]
        : []),
      'Given the footer, when it is rendered, then it links to every published policy page, contact information and social profiles from theme settings',
      'Given the announcement bar, when a message is edited in the theme editor, then it can be translated per language without code changes',
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'developer',
    depends_on: ['LWC-THM-001'],
    spec_refs: ['/design/interactive_patterns', '/markets/list', '/catalogue/collections_estimate'],
    applies: (doc) => isLiquidTrack(doc),
    agent_prompt: (doc) => `Configure the ${themeName(doc)} header and footer sections. Build the main menu in Online Store > Navigation from the collection structure (about ${doc.catalogue?.collections_estimate ?? 'the agreed number of'} collections)${hasPattern(doc, /mega/i) ? ' and configure the mega-menu with category columns and an image block' : ''}. ${gate(doc, 'markets') || languages(doc).length > 1 ? 'Enable the country and language selectors in header and footer using the localization form so the market is switched by Shopify, not by custom redirects. ' : ''}Footer: policy links, contact details, social links from theme settings and a newsletter sign-up that respects the marketing consent set-up. Verify keyboard navigation, focus states and aria-expanded on menus.`,
  },
  {
    key: 'LWC-THM-003',
    epic: 'theme',
    title: 'Compose the home page and content page templates',
    user_story: 'As a shopper, I want an inspiring home page and clear brand and service pages, so that I understand what makes the brand different before I browse.',
    acceptance_criteria: (doc) => [
      `Given the home page, when it loads on mobile, then the hero, featured collections and brand story communicate ${listOr(doc.brand?.differentiators, 'the brand differentiators')} above and just below the fold`,
      'Given the About, Contact, FAQ and blog templates, when a merchant edits them in the theme editor, then all content comes from sections, blocks or metaobjects and none is hard-coded',
      'Given the 404 and password pages, when they are visited, then they are branded and link back to search and the main collections',
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'developer',
    depends_on: ['LWC-THM-001'],
    spec_refs: ['/brand/differentiators', '/brand/ux_references', '/design/figma/completeness'],
    applies: (doc) => isLiquidTrack(doc),
    agent_prompt: (doc) => `Compose the home page in the ${themeName(doc)} theme editor from existing sections and blocks: hero (image or video with explicit dimensions and fetchpriority high), featured collections, brand story (${listOr(doc.brand?.differentiators, 'differentiators to confirm')}), social proof and newsletter. Create JSON templates for About, Contact (contact form), FAQ (collapsible content block) and blog/article pages. UX references: ${listOr(doc.brand?.ux_references, 'none given')}. Keep LCP image optimised with image_url widths and sizes. Present screenshots for designer approval.`,
  },
  {
    key: 'LWC-THM-004',
    epic: 'theme',
    title: 'Build collection and search results pages with filters and predictive search',
    user_story: 'As a shopper, I want to filter, sort and search the catalogue quickly, so that I find the right product in a few steps.',
    acceptance_criteria: (doc) => [
      `Given a collection page, when filters are applied, then ${listOr(doc.catalogue?.custom_attributes, 'availability, price and product type')} filters from Search & Discovery update results without a full page reload and the URL is shareable`,
      'Given the header search, when a shopper types three characters, then predictive search shows products, collections and pages within 300 ms on a mid-range mobile',
      'Given a search with no results, when the results page renders, then it suggests popular collections and Search & Discovery synonyms are applied',
      `Given the product grid, when it renders on mobile, then product cards show image, title, price${hasPattern(doc, /quick/i) ? ', quick-add' : ''} and badges without layout shift`,
    ],
    gaia_tier: 'T2',
    points: 5,
    owner: 'developer',
    depends_on: ['LWC-THM-001', 'LWC-CAT-002', 'LWC-CAT-003'],
    gates: ['search_merchandising'],
    spec_refs: ['/catalogue/custom_attributes', '/catalogue/collection_mode', '/design/interactive_patterns'],
    applies: (doc) => isLiquidTrack(doc),
    agent_prompt: (doc) => `Configure the collection (main-collection) and search templates in ${themeName(doc)}. Enable storefront filtering with the Shopify Search & Discovery app: availability, price, product type, vendor${doc.catalogue?.custom_attributes?.length ? ` and metafield filters for ${list(doc.catalogue.custom_attributes)}` : ''}. Configure sort options, pagination or load-more, product card content${hasPattern(doc, /quick/i) ? ' and quick-add' : ''}. Enable predictive search in the header and set up synonyms and boosts in Search & Discovery. Test filters with keyboard and screen reader and check CLS stays below 0.1 when filtering.`,
  },
  {
    key: 'LWC-THM-005',
    epic: 'theme',
    title: 'Build the product page with media gallery, variant picker and trust content',
    user_story: 'As a shopper, I want rich product media, clear variant choices and reassurance about delivery and returns, so that I can buy with confidence.',
    acceptance_criteria: (doc) => [
      `Given a product with up to ${doc.catalogue?.variants_per_product_max ?? 'the maximum number of'} variants, when a shopper picks options, then price, availability, media and URL update to the selected variant${hasPattern(doc, /swatch/i) ? ' and colour/material options render as swatches' : ''}`,
      `Given product metafields, when the page renders, then ${listOr(doc.catalogue?.custom_attributes, 'specification attributes')} are shown in a specification block driven by dynamic sources`,
      'Given the buy box, when it is viewed on mobile, then the price, add to cart, accelerated checkout buttons, delivery estimate and returns summary are visible without scrolling past the gallery',
      'Given the page source, when structured data is validated, then Product JSON-LD with offers is valid in the Rich Results Test',
    ],
    gaia_tier: 'T2',
    points: 5,
    owner: 'developer',
    depends_on: ['LWC-THM-001', 'LWC-CAT-001'],
    spec_refs: ['/catalogue/variants_per_product_max', '/catalogue/custom_attributes', '/design/interactive_patterns', '/shipping/returns/policy'],
    applies: (doc) => isLiquidTrack(doc),
    agent_prompt: (doc) => `Configure the ${themeName(doc)} product template: media gallery (zoom, video, 3D if supplied), variant picker${hasPattern(doc, /swatch/i) ? ' with swatches driven by the Shopify category metafield/metaobject swatch values' : ''}, price with unit price and tax-inclusive note where required by market, quantity, add to cart and dynamic checkout buttons. Add a specification block bound via dynamic sources to ${listOr(doc.catalogue?.custom_attributes, 'the product metafields')} and trust blocks for delivery, returns (${doc.shipping?.returns?.policy ?? 'policy to confirm'}) and warranty. Add a complementary products block powered by Search & Discovery recommendations. Validate Product structured data and check keyboard operation of the variant picker.`,
  },
  {
    key: 'LWC-THM-006',
    epic: 'theme',
    title: 'Configure the cart drawer and cart page',
    user_story: 'As a shopper, I want to review and edit my cart without leaving the page, so that I can check out quickly.',
    acceptance_criteria: (doc) => [
      'Given a product is added, when the cart drawer opens, then quantity changes and removals update totals via the Cart AJAX API without a page reload and announce the change to screen readers',
      ...((doc.shipping?.rates ?? []).includes('free_above_threshold') || (doc.shipping?.free_shipping_thresholds ?? []).length ? ['Given a free-shipping threshold, when the cart subtotal changes, then a progress message shows the remaining amount in the market currency'] : []),
      `Given the cart, when a shopper proceeds, then accelerated checkout buttons and the discount code field behave as configured${isB2b(doc) ? ' and B2B buyers see their catalog prices and quantity rules' : ''}`,
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'developer',
    depends_on: ['LWC-THM-005'],
    spec_refs: ['/shipping/rates', '/design/interactive_patterns', '/promotions/discount_types'],
    applies: (doc) => isLiquidTrack(doc),
    agent_prompt: (doc) => `Configure the ${themeName(doc)} cart drawer and cart page: line items with variant options and properties, quantity controls, remove, cart note if needed, subtotal with market currency, estimated shipping message${doc.shipping?.rates === 'free_threshold' || doc.shipping?.rates === 'mixed' ? ', free-shipping progress bar with the threshold read from a theme setting per market (not hard-coded)' : ''} and accelerated checkout buttons. Use the Cart AJAX API and the theme's section rendering; announce updates with aria-live. Test with multiple currencies${isB2b(doc) ? ' and with a B2B buyer logged in' : ''}.`,
  },
  {
    key: 'LWC-THM-007',
    scope: 'Build the bespoke sections as theme blocks',
    epic: 'theme',
    title: (doc) => `Build custom ${storeName(doc)} sections as ${themeName(doc)} theme blocks`,
    user_story: 'As a merchandiser, I want the bespoke design elements available as reusable blocks in the theme editor, so that I can build pages without a developer.',
    acceptance_criteria: [
      'Given each approved custom design element, when it is built, then it is a theme block in blocks/ with a valid schema, presets and translatable setting labels',
      'Given a merchant in the theme editor, when they add the block to any section that accepts theme blocks, then all content and styling options come from settings with no hard-coded brand values',
      'Given Theme Check and the accessibility checks, when the blocks are reviewed, then there are no errors and each block works on mobile and desktop',
    ],
    gaia_tier: 'T3',
    points: 8,
    owner: 'developer',
    depends_on: ['LWC-THM-001'],
    gates: ['storefront_design'],
    spec_refs: ['/design/custom_design', '/design/figma/completeness', '/design/figma/mapped_to_sections', '/design/interactive_patterns'],
    applies: (doc) => isLiquidTrack(doc) && (doc.design?.custom_design === true || ['key_screens', 'all_templates'].includes(doc.design?.figma?.completeness)),
    agent_prompt: (doc) => `Map each Figma component that the standard ${themeName(doc)} blocks cannot reproduce to a new theme block (Online Store 2.0): create blocks/<name>.liquid with {% schema %} settings, presets and translation keys in locales/en.default.schema.json, render nested blocks with {% content_for 'blocks' %} where the block is a container, and use static blocks only where layout must be fixed. Do not register sections in config/settings_schema.json — that file holds global theme settings only. Figma mapped to sections: ${doc.design?.figma?.mapped_to_sections ? 'yes' : 'no — produce the mapping first and get designer approval'}. Validate every block with Theme Check and the Shopify Liquid schema validator before pushing.`,
  },
  {
    key: 'LWC-THM-008',
    epic: 'theme',
    title: 'Add motion and micro-interactions that respect reduced-motion preferences',
    user_story: 'As a shopper, I want subtle, purposeful motion, so that the store feels premium without slowing me down.',
    acceptance_criteria: [
      'Given a visitor with prefers-reduced-motion set, when they browse, then all non-essential animation is disabled',
      'Given animations on scroll and hover, when the page is profiled, then they use transform and opacity only and add no layout shift or long tasks over 50 ms',
      'Given the theme editor, when a merchant toggles animations off in theme settings, then no animation runs anywhere',
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'developer',
    depends_on: ['LWC-THM-001'],
    spec_refs: ['/design/motion', '/design/performance/inp_ms'],
    applies: (doc) => isLiquidTrack(doc) && doc.design?.motion === true,
    agent_prompt: (doc) => `Use the ${themeName(doc)} built-in animation settings first (reveal on scroll, hover effects). Add only the motion the designer specified, in CSS with transform/opacity, behind a theme setting and a prefers-reduced-motion media query. Do not add animation libraries. Profile INP (target ${doc.design?.performance?.inp_ms ?? 200} ms) and CLS before and after.`,
  },
  {
    key: 'LWC-THM-009',
    epic: 'theme',
    title: 'Support right-to-left languages across the theme',
    user_story: 'As a shopper reading a right-to-left language, I want the layout mirrored correctly, so that the store is natural to use.',
    acceptance_criteria: [
      'Given an RTL language is selected, when any template renders, then the html dir attribute is rtl and layout, icons and carousels are mirrored',
      'Given custom CSS, when it is reviewed, then it uses logical properties (margin-inline, inset-inline) instead of left/right',
      'Given checkout and customer accounts, when viewed in the RTL language, then Shopify-hosted pages render RTL without theme changes',
    ],
    gaia_tier: 'T2',
    points: 5,
    owner: 'developer',
    depends_on: ['LWC-THM-001', 'LWC-MKT-002'],
    spec_refs: ['/markets/rtl_required', '/markets/list/*/languages'],
    applies: (doc) => isLiquidTrack(doc) && doc.markets?.rtl_required === true,
    agent_prompt: (doc) => `Enable RTL support for ${listOr(languages(doc), 'the RTL languages')} in ${themeName(doc)}: set dir from request.locale on the html element, convert any custom CSS to logical properties, mirror directional icons and slider behaviour, and test every template in an RTL locale. Do not fork templates per direction.`,
  },
  /*
   * The headless track.
   *
   * There was one story here and I deleted it in the commit that sent headless
   * out of the offers. Headless came back two commits later as an L trigger and
   * the story did not, so a Hydrogen engagement produced a backlog with no
   * storefront work in it at all — 58 stories against 64, and none of the six
   * theme ones, because every guard above reads isLiquidTrack.
   *
   * One story would not have been enough either. A theme build gets six; a
   * headless build has to earn the same ground from scratch, and the decisions
   * it makes in the first fortnight are the ones the offer is bought for.
   */
  {
    key: 'LWC-THM-010',
    epic: 'theme',
    title: 'Choose the route structure, rendering strategy and caching model',
    user_story: 'As the client, I want the front-end architecture decided and written down, so that the choices we live with for years were made deliberately and can be explained.',
    description: (doc) => `Hosting: ${doc.design?.headless?.hosting ?? 'to confirm'}. Content source: ${doc.design?.headless?.content_source ?? 'to confirm'}. Reasons given: ${listOr(doc.design?.headless?.reasons, 'to confirm')}.`,
    acceptance_criteria: [
      'Given the template set, when the route structure is agreed, then every page type has a route and the product URL pattern is either Shopify\u2019s /products/:handle or has a server-side redirect from it',
      'Given each route, when the rendering strategy is decided, then it says server-rendered, streamed or client-side and why, and the caching policy per route is written beside it',
      'Given buyer-specific routes, when caching is set, then they are not cached, because those queries return personalised data',
      'Given the decision record, when it is handed over, then it says what the architecture rules out and what it would take to change it',
    ],
    gaia_tier: 'T3',
    points: 8,
    owner: 'developer',
    depends_on: ['LWC-FND-002'],
    spec_refs: ['/design/headless_required', '/design/headless/reasons', '/design/headless/hosting', '/design/headless/content_source'],
    applies: (doc) => !isLiquidTrack(doc),
    agent_prompt: (doc) => `Design the Hydrogen route structure for ${storeName(doc)} against the agreed template set. Decide and document the rendering strategy and cache policy per route, keeping buyer-specific routes uncached because their queries are personalised. Keep Shopify's /products/:handle pattern, or provide server-side 3XX redirects from it. Write the decision record: why headless, what it rules out, what it costs to keep, and what reverting would take.`,
  },
  {
    key: 'LWC-THM-011',
    epic: 'theme',
    title: 'Set up Oxygen environments and the deployment pipeline',
    user_story: 'As a developer, I want environments and deploys that somebody owns, so that a broken route on a Friday has a known path back.',
    acceptance_criteria: (doc) => [
      'Given the repository, when a branch is pushed, then it deploys to its own environment and the production branch deploys to production',
      `Given the ${doc.shopify?.target_plan === 'plus' ? 'Plus plan' : 'plan below Plus'}, when review links are agreed, then who reviews where is written down\u2014only one environment can be public below Plus, against 25 on Plus, and every other deployment needs a store login`,
      'Given a custom domain, when consent is tested, then the cookie banner works, because it does not work on default Oxygen URLs',
      'Given a bad deploy, when the rollback is rehearsed before launch, then the time it takes is measured rather than assumed',
      'Given deploy rights, when they are granted, then who may deploy to production is a named list',
    ],
    gaia_tier: 'T3',
    points: 5,
    owner: 'developer',
    depends_on: ['LWC-THM-010'],
    spec_refs: ['/design/headless/hosting', '/shopify/target_plan', '/compliance/consent_approach'],
    applies: (doc) => !isLiquidTrack(doc),
    agent_prompt: (doc) => `Set up Oxygen environments (${doc.design?.headless?.hosting ?? 'confirm hosting first'}): production on the default branch, preview for the rest, and custom environments where the workstreams need them. Below Plus only one environment can be public, so agree explicitly who reviews where. Attach the custom domain before testing consent \u2014 Hydrogen's cookie banner does not work on default Oxygen URLs. Rehearse and time a rollback. Record who may deploy to production.`,
  },
  {
    key: 'LWC-THM-012',
    epic: 'theme',
    title: 'Build the design system as components over one token layer',
    user_story: 'As the client, I want one token layer behind every component, so that a brand change is a token change and not a rebuild.',
    acceptance_criteria: (doc) => [
      'Given the design source, when the token layer is built, then colour, type, spacing and motion come from it and no component carries a hard-coded brand value',
      'Given the component library, when it is reviewed, then components are composed rather than traced page by page, and the client\u2019s own team can read and extend them',
      `Given every template in the set, when it is built against the system, then it matches the design${doc.design?.motion ? ' including the specified motion and interaction' : ''} and respects reduced-motion`,
      'Given the library, when it is handed over, then it has tests and a way to see a component in isolation',
    ],
    gaia_tier: 'T3',
    points: 13,
    owner: 'developer',
    depends_on: ['LWC-THM-010'],
    spec_refs: ['/design/figma/completeness', '/design/figma/design_system', '/design/motion', '/brand/has_guidelines'],
    gates: ['storefront_design'],
    applies: (doc) => !isLiquidTrack(doc),
    agent_prompt: (doc) => `Build the component library for ${storeName(doc)} from one token layer. No hex values, font names or radii inside components. Compose templates from components rather than tracing each page.${doc.design?.motion ? ' Implement the specified motion and interaction, and honour prefers-reduced-motion.' : ''} Add component tests and an isolated preview. Present it for designer approval before the templates are built out.`,
  },
  {
    /* One design serves every market and every store in every pack, so a second
       one is a second theme: Shopify's per-market customisation reaches section
       content, block visibility and order, and section-level settings — never
       theme settings and never Liquid templates. The design system is not built twice — this set is drawn
       against the same token layer, which is what keeps it an add-on rather
       than a second programme. */
    key: 'LWC-THM-016',
    epic: 'theme',
    title: 'Build each further storefront design against the same token layer',
    user_story: 'As a brand with a storefront that has to look genuinely different in one market or channel, I want a second design built on the same design system, so that it is a different layout rather than a second brand to maintain',
    acceptance_criteria: [
      'Given the approved second design, when it is built, then every template in the set is composed from the existing token layer and no new tokens, type ramp or colour values are introduced',
      'Given the second theme, when it is installed, then it has its own theme settings and passes Theme Check and the accessibility checks, and the first theme is unchanged',
      'Given both designs, when a shared component changes, then the change is applied to each and the release notes name every theme it went to',
    ],
    gaia_tier: 'T3',
    points: 13,
    owner: 'developer',
    depends_on: ['LWC-THM-001'],
    spec_refs: ['/design/extra_theme_designs'],
    gates: ['theme_design'],
    applies: (doc) => (doc.design?.extra_theme_designs ?? 0) > 0,
    agent_prompt: (doc) => `Build ${doc.design?.extra_theme_designs ?? 1} further storefront design${(doc.design?.extra_theme_designs ?? 1) === 1 ? '' : 's'} for ${storeName(doc)} against the token layer the first one already established. Reuse the tokens and the components; change the layout and the page structure, not the system. Each design is its own theme with its own settings — theme licences are not shared between stores — so plan how a shared component change reaches every one of them before the first is signed off. If what is being asked for is a second brand with its own full design system, stop: that is a design-system programme per brand and it leaves the offers (rule 11.29).`,
  },
  {
    /* A page template designed and built new while the storefront stays on a
       Shopify theme — how a large, global set-up keeps its theme and still
       gets the pages it needs. A full template set builds every template and
       carries this, so it never applies beside the bespoke tier. */
    key: 'LWC-THM-017',
    epic: 'theme',
    title: 'Design and build each custom template on the Shopify theme',
    user_story: 'As a brand that keeps a Shopify theme, I want the few pages that matter designed and built as templates of their own, so that they look like the brand without the whole storefront becoming a custom theme',
    acceptance_criteria: [
      'Given each custom template, when it is designed, then the design uses the theme\'s own tokens and components and names what is new in it',
      'Given the design, when the template is built, then it is a JSON template of the theme composed of sections and blocks the merchant can still rearrange, and it passes Theme Check and the accessibility checks',
      'Given the products, collections or pages that use it, when it is assigned, then each one renders with it on the real catalogue and the others keep the default',
    ],
    gaia_tier: 'T2',
    points: 5,
    owner: 'developer',
    depends_on: ['LWC-THM-001'],
    spec_refs: ['/design/custom_templates'],
    gates: ['custom_templates'],
    applies: (doc) => (doc.design?.custom_templates ?? 0) > 0 && doc.offer?.scope_gates?.storefront_design?.tier !== 'bespoke',
    agent_prompt: (doc) => `Design and build ${doc.design?.custom_templates ?? 1} custom page template${(doc.design?.custom_templates ?? 1) === 1 ? '' : 's'} on the Shopify theme for ${storeName(doc)}. Each is an alternate JSON template of the theme — a template of its own for the products, collections or pages that need it — built from the theme's tokens, sections and blocks, so the merchant can still rearrange it. Shopify allows 1,000 JSON templates per theme. If the list grows past eight, stop and raise it: at that size the storefront is a full template set and is priced as one.`,
  },
  {
    key: 'LWC-THM-013',
    epic: 'theme',
    title: 'Render editorial content from Shopify metaobjects',
    user_story: 'As a marketer, I want to change page content without a deploy, so that a campaign does not wait for an engineer.',
    acceptance_criteria: [
      'Given the content the storefront renders, when metaobject definitions are created, then each has the fields the templates need and an editor can fill them in the admin',
      'Given a content change in the admin, when the page is reloaded, then it appears without a code change or a deploy',
      'Given the editing experience, when it is handed over, then the client knows which content they can change themselves and which is in code',
      'Given content that must differ per market or language, when it is modelled, then the translation route is the same one the rest of the storefront uses',
    ],
    gaia_tier: 'T3',
    points: 8,
    owner: 'developer',
    depends_on: ['LWC-THM-010', 'LWC-CAT-001'],
    spec_refs: ['/design/headless/content_source', '/catalogue/custom_attributes'],
    applies: (doc) => !isLiquidTrack(doc),
    agent_prompt: () => 'Model the editorial content as Shopify metaobjects and render it through the Storefront API. Content stays in Shopify \u2014 that is what keeps this a Shopify build rather than a composable one. Give editors a usable admin experience and write down exactly what they can change without a developer.',
  },
  {
    key: 'LWC-THM-014',
    epic: 'theme',
    title: (doc) => `Build cart, checkout hand-off and customer accounts on the Storefront API${languages(doc).length > 1 || gate(doc, 'markets') ? ' across the markets' : ''}`,
    user_story: 'As a shopper, I want to add to cart, check out and see my orders, so that a headless storefront does everything the theme would have done.',
    acceptance_criteria: (doc) => [
      'Given a cart, when the buyer is ready, then the storefront hands off to Shopify\u2019s checkout using the cart\u2019s checkoutUrl rather than reimplementing checkout',
      'Given a returning customer, when they sign in, then it is through the Customer Account API and they can see orders, addresses and profile',
      ...(gate(doc, 'markets') || languages(doc).length > 1 ? ['Given the markets in scope, when a buyer arrives, then the storefront sets the market and language context on the cart and the prices shown are the market\u2019s own'] : []),
      ...(gate(doc, 'b2b') ? ['Given a B2B buyer, when they sign in, then company accounts work through customer accounts, because B2B has no other route in a headless storefront'] : []),
    ],
    gaia_tier: 'T3',
    points: 8,
    owner: 'developer',
    depends_on: ['LWC-THM-010'],
    spec_refs: ['/design/headless/features', '/markets/list', '/b2b/enabled'],
    applies: (doc) => !isLiquidTrack(doc),
    agent_prompt: (doc) => `Implement cart and customer accounts against the Storefront API and the Customer Account API. Hand off to Shopify's checkout by the cart's checkoutUrl \u2014 never reimplement checkout.${gate(doc, 'markets') ? ' Set market and language context on the cart so international prices are correct.' : ''}${gate(doc, 'b2b') ? ' B2B works only through customer accounts, so build company account sign-in on that route.' : ''} Test signed-out and signed-in journeys on every market in scope.`,
  },
  {
    key: 'LWC-THM-015',
    epic: 'theme',
    title: 'Wire analytics and consent on the headless storefront',
    user_story: 'As a marketer, I want the numbers from a headless storefront to agree with Shopify\u2019s, so that nobody argues about which report is right.',
    acceptance_criteria: [
      'Given the storefront, when analytics is wired, then it uses Hydrogen\u2019s own analytics so the figures reach Shopify admin alongside the orders',
      'Given consent, when it is tested, then the banner works on the custom domain, because it does not work on default Oxygen URLs',
      'Given a shopper who refuses consent, when they browse and buy, then nothing that needed consent has fired',
      'Given the first week after launch, when Shopify\u2019s numbers are compared with the external destinations, then the difference is explained rather than noticed later',
    ],
    gaia_tier: 'T3',
    points: 5,
    owner: 'developer',
    depends_on: ['LWC-THM-011'],
    spec_refs: ['/design/headless/features', '/marketing/analytics', '/compliance/consent_approach'],
    gates: ['analytics_consent'],
    applies: (doc) => !isLiquidTrack(doc),
    agent_prompt: () => 'Wire Hydrogen analytics so storefront metrics reach Shopify admin, and implement consent with the customer privacy API. Test the banner on the custom domain rather than the Oxygen URL, where it does not work. Verify that refusing consent fires nothing that needed it, and reconcile Shopify\u2019s numbers against the external destinations in week one.',
  },
];
