import { index, route } from '@react-router/dev/routes';

export default [
  index('routes/home.jsx'),
  route('login', 'routes/login.jsx'),
  route('auth/github', 'routes/auth.github.js'),
  route('auth/github/callback', 'routes/auth.github.callback.js'),
  route('logout', 'routes/logout.js'),
  route('engagements/:client', 'routes/engagement.jsx'),
  route('engagements/:client/review', 'routes/engagement.review.jsx'),
  route('engagements/:client/summary', 'routes/engagement.summary.jsx'),
  route('engagements/:client/summary.md', 'routes/engagement.summary-md.js'),
  route('engagements/:client/closing-document', 'routes/engagement.closing.jsx'),
  route('engagements/:client/closing-document.md', 'routes/engagement.closing-md.js'),
  route('engagements/:client/closing-document.pptx', 'routes/engagement.closing-pptx.js'),
  route('engagements/:client/closing-annex.md', 'routes/engagement.closing-annex.js'),
  route('engagements/:client/closing-preview', 'routes/engagement.closing-preview.js'),
  route('engagements/:client/go-no-go', 'routes/engagement.go-no-go.jsx'),
  route('engagements/:client/handover', 'routes/engagement.handover.jsx'),
  route('engagements/:client/handover-backlog.csv', 'routes/engagement.handover-file.js', { id: 'handover-backlog-csv' }),
  route('engagements/:client/handover-backlog.md', 'routes/engagement.handover-file.js', { id: 'handover-backlog-md' }),
  route('engagements/:client/handover-workbook.md', 'routes/engagement.handover-file.js', { id: 'handover-workbook-md' }),
  route('engagements/:client/settings', 'routes/engagement.settings.jsx'),
  route('engagements/:client/clarifications', 'routes/engagement.clarifications.jsx'),
  route('engagements/:client/clarifications.md', 'routes/engagement.clarifications-md.js'),
  route('engagements/:client/questions/:questionId', 'routes/engagement.question.jsx'),
  route('offering', 'routes/offering.jsx'),
  route('offering/estimation', 'routes/offering.estimation.jsx'),
  route('offering/:segment', 'routes/offering.segment.jsx'),
  route('about', 'routes/about.jsx'),
  route('how-it-works', 'routes/how-it-works.jsx'),
  route('claude', 'routes/claude.jsx'),
  route('manual', 'routes/manual.jsx'),
  route('manual/bid', 'routes/manual.bid.jsx'),
  route('manual/discovery', 'routes/manual.discovery.jsx'),
  // Claude connector (ADR 0015): MCP endpoint and OAuth
  route('mcp', 'routes/mcp.js'),
  route('.well-known/oauth-authorization-server', 'routes/well-known.authorization-server.js'),
  route('.well-known/oauth-protected-resource', 'routes/well-known.protected-resource.js', { id: 'protected-resource' }),
  route('.well-known/oauth-protected-resource/mcp', 'routes/well-known.protected-resource.js', { id: 'protected-resource-mcp' }),
  route('oauth/authorize', 'routes/oauth.authorize.jsx'),
  route('oauth/token', 'routes/oauth.token.js'),
];
