/**
 * The configuration workbook in the client's language.
 *
 * It is handed to the client's finance and logistics teams to fill in, which
 * makes it as client-facing as the proposal — and it was the last thing the tool
 * produced that came out in English whatever language the engagement was run in.
 * It is not a prompt, so there was no instruction to add: it is Markdown
 * generated by code, and the only fix was the words themselves.
 */
import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

import { buildWorkbook } from '../../workbook/build.js';
import { words, WORKBOOK_LANGUAGES } from '../../workbook/strings.js';
import { LANGUAGES } from '../../shared/i18n.js';
import { assemble } from '../../engine/engine.js';

const fixture = JSON.parse(fs.readFileSync(
  path.join(import.meta.dirname, '..', 'fixtures', 'engagements', 'acme-watches.json'), 'utf8'));

describe('the workbook’s words', () => {
  test('exist in every language an engagement can be run in', () => {
    assert.deepEqual(WORKBOOK_LANGUAGES.sort(), [...LANGUAGES].sort(),
      'a language the tool offers but the workbook has no words for would silently fall back to English');
  });

  test('every key is present in all three, with the same shape', () => {
    // A missing key is not a fallback here: `W.subDuties` would render as
    // "undefined" in the middle of a document a client fills in.
    const en = words('en');
    for (const language of WORKBOOK_LANGUAGES.filter((l) => l !== 'en')) {
      const other = words(language);
      assert.deepEqual(Object.keys(other).sort(), Object.keys(en).sort(), `${language}: same keys`);
      for (const [key, value] of Object.entries(en)) {
        assert.equal(typeof other[key], typeof value, `${language}.${key}: same type`);
        if (Array.isArray(value)) {
          other[key].forEach((s) => assert.ok(String(s).trim(), `${language}.${key}: no empty entry`));
          // `intro` is wrapped prose, not a list of parallel items: German runs
          // longer than English and takes a line more. Everything else is a set
          // of table headers, where the count is the table's shape.
          if (key !== 'intro') {
            assert.equal(other[key].length, value.length, `${language}.${key}: same number of entries`);
          }
        } else if (typeof value === 'string') {
          assert.ok(other[key].trim(), `${language}.${key}: not empty`);
        }
      }
    }
  });

  test('the intro stays a blockquote in every language, separator and all', () => {
    // Its line count is free; its shape is not. A line that lost its "> " would
    // fall out of the quote and read as body text in the middle of the intro.
    for (const language of WORKBOOK_LANGUAGES) {
      const intro = words(language).intro;
      intro.forEach((line, i) => assert.match(line, /^>( |$)/, `${language}: intro line ${i}`));
      assert.ok(intro.includes('>'), `${language}: the blank quoted line before the security warning`);
      assert.match(intro.at(-1), /\*\*/, `${language}: the security line is still bold`);
    }
  });

  test('table headers keep their column count, or the table stops lining up', () => {
    const en = words('en');
    const headers = Object.keys(en).filter((k) => k.startsWith('th'));
    assert.ok(headers.length >= 15, 'the workbook has tables and this test found them');
    for (const language of WORKBOOK_LANGUAGES) {
      for (const key of headers) {
        assert.equal(words(language)[key].length, en[key].length, `${language}.${key}`);
      }
    }
  });
});

describe('what the workbook says, in three languages', () => {
  const build = (language) => buildWorkbook(fixture, { language });

  test('an engagement with no language recorded gets English, unchanged', () => {
    // Everything generated before meta.language existed still has to render.
    const { language, ...noLanguage } = fixture.meta;
    assert.equal(buildWorkbook({ ...fixture, meta: noLanguage }), build('en'));
    assert.equal(buildWorkbook(fixture, { language: undefined }), build('en'));
  });

  test('the German and French workbooks are German and French from the title down', () => {
    assert.match(build('de'), /^# Konfigurationshandbuch für den Store/);
    assert.match(build('fr'), /^# Cahier de configuration de la boutique/);
    for (const language of ['de', 'fr']) {
      const md = build(language);
      const W = words(language);
      for (const key of ['secTax', 'secShipping', 'secSignOff', 'subRegistrations', 'subZones', 'subReturns']) {
        assert.ok(md.includes(W[key]), `${language}: missing ${key}`);
      }
      assert.ok(!md.includes('Tax and duties'), `${language}: an English section title survived`);
      assert.ok(!md.includes('_to complete_'), `${language}: an English placeholder survived`);
    }
  });

  test('the security line survives translation — it is the one line that must be read', () => {
    // Never enter passwords, API keys or carrier credentials in this document.
    assert.match(build('de'), /niemals Passwörter, API-Schlüssel oder Zugangsdaten/);
    assert.match(build('fr'), /jamais de mots de passe, de clés d'API/);
  });

  test('Shopify’s own names and the customs vocabulary are left alone', () => {
    // Renaming a Shopify feature makes it uncheckable against the page that
    // proves it; renaming a customs regime makes a legal obligation
    // unsearchable. The admin path is what the client has to find on screen.
    for (const language of WORKBOOK_LANGUAGES) {
      const md = build(language);
      for (const keep of ['Shopify Tax', 'IOSS', 'Peppol', 'XRechnung', 'SdI', 'KSeF', 'Settings > Taxes and duties']) {
        assert.ok(md.includes(keep), `${language}: lost "${keep}"`);
      }
    }
  });

  test('DDP and DAP stay as they are — they are Incoterms, not words', () => {
    const withDuties = { ...fixture, markets: { ...fixture.markets, duties_ddp: true } };
    for (const language of WORKBOOK_LANGUAGES) {
      const md = buildWorkbook(withDuties, { language });
      assert.ok(md.includes('DDP') && md.includes('DAP'), language);
    }
  });

  test('the same tables come out, whatever the language', () => {
    // A translated header that lost or gained a column would break the Markdown
    // table the client types into.
    const rows = (md) => md.split('\n').filter((l) => l.startsWith('|'));
    const columns = (line) => line.split('|').length;
    const base = rows(build('en'));
    for (const language of ['de', 'fr']) {
      const other = rows(build(language));
      assert.equal(other.length, base.length, `${language}: same number of table rows`);
      other.forEach((line, i) => assert.equal(columns(line), columns(base[i]), `${language}: row ${i} column count`));
    }
  });
});

describe('the engagement carries the language the workbook needs', () => {
  test('the engine stamps it on meta, so anything generated from engagement.json knows', () => {
    // The workbook is a CLI over clients/<slug>/engagement.json. Without this it
    // had no way to know the language, however well translated it was.
    const answers = { meta: { client: { slug: 'demo', name: 'Demo AG' } } };
    assert.equal(assemble(answers, { today: '2026-09-20', language: 'de' }).meta.language, 'de');
    assert.equal(assemble(answers, { today: '2026-09-20', language: 'en' }).meta.language, 'en');
    assert.equal('language' in assemble(answers, { today: '2026-09-20' }).meta, false,
      'no language recorded means no claim about it, not a guess of English');
  });
});
