/**
 * @file render.js
 * @description Markdown renderings of an engagement document (ADR 0002).
 * GO → delivery-plan.md, capability-map.md, app-shortlist.md, risks.md.
 * STOP → stop-report.md only. Internal pricing and modifiers are never rendered.
 *
 * @module discovery/render
 */

const RESOLUTION_LABEL = { native: 'Native', app: 'App', theme: 'Theme', custom: 'Custom' };
const RESOLUTION_ORDER = ['native', 'app', 'theme', 'custom'];

/** Escape pipes and newlines so free text cannot break a Markdown table. */
const cell = (value) => String(value ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');

/**
 * @param {string[]} headers
 * @param {unknown[][]} rows
 */
function table(headers, rows) {
  if (rows.length === 0) return '_None._';
  return [
    `| ${headers.join(' | ')} |`,
    `|${headers.map(() => '---').join('|')}|`,
    ...rows.map((r) => `| ${r.map(cell).join(' | ')} |`),
  ].join('\n');
}

/** @param {object} doc */
function header(doc, title) {
  const c = doc.meta.client;
  return [
    `# ${title} — ${c.name}`,
    '',
    `> Generated by the discovery engine from \`engagement.json\` · ${doc.meta.updated_at ?? doc.meta.created_at ?? ''}`,
    `> Offer: **${doc.offer.code} — ${doc.offer.name}** (${doc.offer.delivery_track}) · Status: **${doc.delivery.go ? 'GO' : 'STOP'}**`,
    '> Edit `engagement.json`, not this file.',
    '',
  ].join('\n');
}

/** @param {object} doc */
function renderCapabilityMap(doc) {
  const rows = [...(doc.approach.capability_map ?? [])]
    .sort((a, b) => RESOLUTION_ORDER.indexOf(a.resolution) - RESOLUTION_ORDER.indexOf(b.resolution))
    .map((r) => [r.requirement, RESOLUTION_LABEL[r.resolution], r.tool, r.gaia_tier, r.notes, (r.question_ids ?? []).join(', ')]);
  return `${header(doc, 'Capability Map')}
Resolution order: Native → App → Theme → Custom.

${table(['Requirement', 'Resolution', 'Tool / feature', 'Gaia tier', 'Notes', 'Questions'], rows)}
`;
}

/** @param {object} app */
function cost(app) {
  if (!app.cost?.amount && app.cost?.amount !== 0) return app.cost?.note ?? '';
  const period = { month: '/mo', year: '/yr', one_off: ' one-off', usage: ' usage-based' }[app.cost.period] ?? '';
  return `${app.cost.currency ?? ''} ${app.cost.amount}${period}${app.cost.note ? ` (${app.cost.note})` : ''}`.trim();
}

/** @param {object} doc */
function renderAppShortlist(doc) {
  const apps = doc.approach.app_shortlist ?? [];
  const recommended = apps.filter((a) => a.recommended);
  const rejected = apps.filter((a) => !a.recommended);
  return `${header(doc, 'App Shortlist')}
## Recommended

${table(['App', 'Requirement', 'Why', 'Limitations', 'Cost', 'Integration', 'Gaia tier'],
    recommended.map((a) => [a.url ? `[${a.name}](${a.url})` : a.name, a.requirement, a.rationale, a.limitations, cost(a), a.integration_complexity, a.gaia_tier]))}

## Evaluated but not recommended

${table(['App', 'Reason'], rejected.map((a) => [a.name, a.rejection_reason]))}

> App costs are list prices at time of discovery — verify on the Shopify App Store.
`;
}

/** @param {object} doc */
function renderDeliveryPlan(doc) {
  const phases = (doc.approach.phases ?? []).map((phase) => {
    const sprints = phase.sprints.map((sprint) => `### ${sprint.name}

${table(['Task', 'Capability', 'Gaia tier', 'Owner', 'Deferred'],
      sprint.tasks.map((t) => [t.title, t.capability ? RESOLUTION_LABEL[t.capability] : '', t.gaia_tier, t.owner, t.deferred ? 'yes' : '']))}`).join('\n\n');
    return `## ${phase.name}\n\n${sprints}`;
  }).join('\n\n');

  const gates = Object.entries(doc.offer.scope_gates)
    .map(([id, g]) => [id.replace(/_/g, ' '), g.active ? 'active' : '—', g.evidence]);

  return `${header(doc, 'Delivery Plan')}
## Scope gates

${table(['Gate', 'Status', 'Evidence'], gates)}

${phases || '_No phases drafted._'}
`;
}

/** @param {object[]} items */
const exitRows = (items) => items.map((i) => [i.rule_id, i.result, i.evidence, i.destination, i.resolution?.owner ?? '', i.resolution?.status ?? '', i.source]);
const EXIT_HEADERS = ['Rule', 'Result', 'Evidence', 'Resolution path', 'Owner', 'Status', 'Source'];

/** @param {object} doc */
function renderRisks(doc) {
  const items = doc.exits.items;
  const risks = doc.approach.risks ?? {};
  return `${header(doc, 'Risks & Open Items')}
## Hard blockers (STOP)

${table(EXIT_HEADERS, exitRows(items.filter((i) => i.result === 'STOP')))}

## Flags (need an owner before build)

${table(EXIT_HEADERS, exitRows(items.filter((i) => i.result === 'FLAG')))}

## Commercial warnings

${table(['Rule', 'Evidence', 'Action'], items.filter((i) => i.result === 'WARN').map((i) => [i.rule_id, i.evidence, i.destination]))}

## Open items (unanswered questions)

${table(['Question', 'Field', 'Why it matters'], (risks.open_items ?? []).map((o) => [o.question_id, o.pointer, o.why]))}

## Assumptions

${table(['Assumption', 'Impact if wrong'], (risks.assumptions ?? []).map((a) => [a.statement, a.impact_if_wrong]))}
`;
}

/** @param {object} doc */
function renderStopReport(doc) {
  const stops = doc.exits.items.filter((i) => i.result === 'STOP' && i.resolution?.status === 'open');
  return `${header(doc, 'STOP Report')}
Discovery cannot close: ${stops.length} hard blocker(s) are open. No delivery plan, capability map
or app shortlist was generated. Resolve or waive each blocker in \`engagement.json\` and re-run.

## Open hard blockers

${table(EXIT_HEADERS, exitRows(stops))}

## Other exit results

${table(EXIT_HEADERS, exitRows(doc.exits.items.filter((i) => !stops.includes(i))))}

## Open items (unanswered questions)

${table(['Question', 'Field', 'Why it matters'], (doc.approach?.risks?.open_items ?? []).map((o) => [o.question_id, o.pointer, o.why]))}
`;
}

/**
 * Render the Markdown artefacts for an engagement.
 *
 * @param {object} doc  Schema-valid engagement document
 * @returns {Record<string, string>}  filename → content
 */
export function renderArtefacts(doc) {
  if (!doc.delivery.go) return { 'stop-report.md': renderStopReport(doc) };
  return {
    'delivery-plan.md': renderDeliveryPlan(doc),
    'capability-map.md': renderCapabilityMap(doc),
    'app-shortlist.md': renderAppShortlist(doc),
    'risks.md': renderRisks(doc),
  };
}
