/**
 * @file strings.js
 * @description Every word of the configuration workbook, in the three languages
 * an engagement can be run in.
 *
 * The workbook is handed to the client's finance and logistics teams to fill in,
 * which makes it as client-facing as the proposal — and it was the last thing the
 * tool produced that was English whatever language the engagement was run in. It
 * is not a prompt, so there was no instruction to add: it is a Markdown template
 * generated by code, and the only honest fix is the words themselves.
 *
 * Three rules held throughout, the same ones the prompts follow:
 *
 *   Shopify's own names stay as they are, including the admin paths a client has
 *   to find on their own screen — translating "Settings > Taxes and duties" would
 *   send them looking for a menu that does not exist in their admin unless their
 *   admin is in that language too, and we do not know that it is.
 *
 *   Customs, tax and standards names are other authorities' proper nouns: IOSS,
 *   Peppol, XRechnung, SdI, KSeF, DDP, DAP, HS codes.
 *
 *   Everything a person reads as a sentence is written in their language, not
 *   carried across word by word.
 *
 * English is the source and is what an engagement with no language recorded gets.
 *
 * @module workbook/strings
 */

import { isEnglish } from '../shared/language.js';

/** @type {Record<string, any>} */
const en = {
  title: (client) => `Store configuration workbook — ${client}`,
  intro: [
    '> **What this is:** the tax and shipping details we need to configure your Shopify store. Your finance and logistics',
    '> teams complete it once the scope is agreed. Values marked *from discovery* come from our discovery sessions — please',
    '> check them. Leave no field empty: write "n/a" or "to decide". Tax and legal decisions stay with your finance team',
    '> and advisers; Merkle configures what you confirm.',
    '>',
    '> **Never enter passwords, API keys or carrier account credentials in this document** — we collect them securely.',
  ],
  china: '_Mainland China is not covered by this workbook: it is handled in a separate China discovery._',
  help: 'Shopify help',
  fromDiscovery: '*(from discovery)*',
  fromDiscoveryConfirm: '*(from discovery — confirm)*',
  toComplete: '_to complete_',
  yes: 'Yes',
  no: 'No',
  ownerFinance: '_Owner: finance_',
  ownerLogistics: '_Owner: logistics and customer service_',
  adminTaxes: 'Shopify admin: Settings > Taxes and duties',
  adminShipping: 'Shopify admin: Settings > Shipping and delivery',

  secTax: 'Tax and duties',
  subTaxService: 'Tax service',
  lblTaxCalculation: 'Tax calculation',
  noteTaxService: '- Shopify Tax calculates the US, EU, UK and Canada; other countries use rates you confirm.',

  subRegistrations: 'Tax registrations',
  proseRegistrations: 'One row per country, state or scheme where you collect tax. Low-value import schemes apply to the EU (IOSS), the UK, Switzerland, Norway, Australia and New Zealand',
  thRegistrations: ['Country, state or scheme', 'Registered?', 'Registration number', 'Collect tax from (date)', 'Notes'],
  rowEuCountries: 'EU countries (list each registration)',
  cellLowValueScheme: 'Low-value import scheme',

  subTaxDisplay: 'Prices and tax display per market',
  proseTaxDisplay: 'Prices can include tax in some markets and exclude it in others',
  proseTaxDisplayTail: 'product prices only, not shipping rates',
  linkTaxDisplay: 'dynamic tax display',
  lblApproach: 'Approach',
  thTaxDisplay: ['Market', 'Currency', 'Prices include tax?', 'Shipping rates include tax?'],

  subDuties: 'Duties and import taxes',
  proseDuties: "Per country, duties are collected at checkout (DDP) or paid by the customer on delivery (DAP) — not both. Collecting duties at checkout can't be combined with tax overrides, manual tax rates or customer tax exemptions, and some destinations are not supported",
  proseDutiesTail: 'Products need HS codes and country of origin.',
  lblHsCodes: 'HS codes and country of origin',
  thDuties: ['Market or country', 'DDP or DAP', 'Carrier and service for DDP shipments', 'Notes'],

  subUsTax: 'US sales tax',
  proseUsTax: 'Add each state where you are registered to collect sales tax',
  proseUsTaxTail: 'In some states (e.g. California, Colorado, Florida, Illinois, Louisiana, Maine, Maryland) you also choose how shipping is taxed.',
  thUsTax: ['State', 'Sales tax ID', 'Registered from (date)', 'Shipping taxed (when applicable / always / never)'],

  subReduced: 'Reduced rates, exemptions and overrides',
  proseReduced: 'Shopify Tax uses product categories for reduced rates and exemptions; overrides apply per country or state to a manual collection',
  lblReducedProducts: 'Products with reduced or zero rates or exemptions',
  thReduced: ['Products or collection', 'Country or state', 'Rate or exemption', 'Legal basis (from your adviser)'],

  subB2bTax: 'B2B tax',
  proseB2bTax: 'Company locations can hold tax registration IDs and exemptions. Automatic EU VAT number validation (reverse charge) needs Shopify Tax, an EU fulfilment location and the "Company VAT number" checkout field',
  lblTaxExempt: 'Tax-exempt business buyers',
  thB2bTax: ['Buyer type or company', 'Country', 'VAT number validated?', 'Exempt or reverse charge?', 'Evidence kept'],

  subInvoices: 'Invoices',
  proseInvoices: 'Shopify can generate VAT invoices for EU and UK orders (shown on the order status page, not emailed, not for orders with duties;',
  proseInvoicesTail: 'E-invoicing (e.g. Peppol, XRechnung, SdI, KSeF) comes from your ERP or an invoicing app.',
  lblInvoiceIssuer: 'Invoices issued by',
  lblEInvoicing: 'E-invoicing obligations',
  thInvoices: ['Legal entity', 'Markets', 'Invoice number format', 'E-invoicing standard', 'Legal text on invoices'],

  secShipping: 'Shipping and delivery',
  subLocations: 'Locations',
  lblFulfilmentModel: 'Fulfilment model',
  thLocations: ['Location name', 'Country', 'Fulfils online orders?', 'Pickup in store?', 'Local delivery?', 'Order cut-off time', 'Processing days'],

  subZones: 'Shipping zones and rates',
  proseZones: 'One row per rate shown at checkout. Cover every weight or order-value range: an order outside all ranges gets a shipping error at checkout.',
  lblRates: 'How rates are calculated',
  thZones: ['Market', 'Countries in the zone', 'Rate name at checkout', 'Service', 'Price, or calculated by carrier', 'Condition (weight or order value)', 'Free above', 'Delivery time shown'],

  subCarriers: 'Carriers and labels',
  lblLabelSource: 'Labels created in',
  thCarriers: ['Carrier', 'Services used', 'Markets', 'Account in place?', 'Tracking link format'],

  subWeights: 'Product weights and packages',
  proseWeights: 'Labels and weight-based or carrier-calculated rates need accurate product weights and a default package',
  lblWeightSource: 'Product weights come from',
  thPackages: ['Package name', 'Type (box, soft pack, envelope)', 'Dimensions', 'Empty weight', 'Default?'],

  subDeliveryDates: 'Delivery dates',
  proseDeliveryDates: 'Shopify can show automated delivery dates for domestic orders in the US and 32 European countries when delivery takes up to 5 days (US) or 4 days (Europe)',
  thDeliveryDates: ['Market', 'Show delivery dates?', 'Typical transit days', 'Holidays or closed days'],

  subLocalDelivery: 'Local delivery',
  proseLocalDelivery: 'Per location: a delivery area by radius (up to 160 km) or postal codes, up to 10 zones and 3 price rules per zone. Not offered at B2B checkout',
  thLocalDelivery: ['Location', 'Area (radius or postal codes)', 'Price rules', 'Minimum order', 'Delivery days and times'],

  subPickup: 'Pickup',
  prosePickupA: 'Pickup in store is set per location',
  prosePickupB: 'Pickup points are native only for stores in France, Italy, Spain and the UK with some carriers; they are not available for B2B or express wallets',
  thPickup: ['Location, carrier or app', 'Type (store pickup / pickup points)', 'Markets', 'Ready for pickup in', 'Pickup instructions'],

  subSpecial: 'Special products and restrictions',
  proseSpecialA: 'Dangerous goods need their own delivery profile and carrier arrangements; the merchant is responsible for classification and labelling',
  proseSpecialB: "Products not allowed in a market are excluded from that market's catalog",
  lblDangerousGoods: 'Dangerous goods',
  lblSpecialRules: 'Product-specific shipping rules',
  lblExcludedCountries: 'Countries you do not ship to',
  lblRestrictedProducts: 'Products restricted in some markets',
  thSpecial: ['Product or collection', 'Rule (dangerous goods / not sold in market / special rate)', 'Markets affected', 'Carrier or service', 'Notes'],

  subB2bShipping: 'B2B shipping',
  proseB2bShipping: 'B2B buyers see the same shipping methods as consumers unless you customise them; orders can be submitted as drafts so shipping is quoted before payment',
  lblB2bRules: 'Rules that differ for B2B',
  thB2bShipping: ['Rule', 'Which buyers or company locations', 'Detail (rates, thresholds, carrier account)'],

  subReturns: 'Return shipping',
  lblReturnWindow: 'Return window (days)',
  lblReturnPaidBy: 'Who pays return shipping',
  lblReturnLabel: 'How items are sent back',
  lblInternationalReturns: 'International returns',
  thReturns: ['Market', 'Return address or location', 'Return fee', 'Carrier or label'],

  secSignOff: 'Sign-off',
  proseSignOff: 'Roles only — no names or contact details in this document.',
  thSignOff: ['Section', 'Confirmed by (role)', 'Date'],

  cliDone: 'store configuration workbook (tax and shipping)',
  cliShare: 'Share with the client once the scope is agreed; finance and logistics complete it before store set-up.',
};

/** @type {Record<string, any>} */
const de = {
  title: (client) => `Konfigurationshandbuch für den Store — ${client}`,
  intro: [
    '> **Worum es geht:** die Angaben zu Steuern und Versand, die wir brauchen, um Ihren Shopify-Store einzurichten. Ihre',
    '> Finanz- und Logistikteams füllen es aus, sobald der Umfang vereinbart ist. Mit *aus der Discovery* markierte Werte',
    '> stammen aus unseren Discovery-Terminen — bitte prüfen Sie sie. Lassen Sie kein Feld leer: schreiben Sie „entfällt“ oder',
    '> „noch zu entscheiden“. Steuerliche und rechtliche Entscheidungen bleiben bei Ihrem Finanzteam und Ihren Beraterinnen',
    '> und Beratern; Merkle konfiguriert, was Sie bestätigen.',
    '>',
    '> **Tragen Sie in dieses Dokument niemals Passwörter, API-Schlüssel oder Zugangsdaten zu Carrier-Konten ein** — die erfassen wir auf sicherem Weg.',
  ],
  china: '_Das chinesische Festland ist nicht Teil dieses Handbuchs: Es wird in einer eigenen China-Discovery behandelt._',
  help: 'Shopify-Hilfe',
  fromDiscovery: '*(aus der Discovery)*',
  fromDiscoveryConfirm: '*(aus der Discovery — bitte bestätigen)*',
  toComplete: '_auszufüllen_',
  yes: 'Ja',
  no: 'Nein',
  ownerFinance: '_Verantwortung: Finanzen_',
  ownerLogistics: '_Verantwortung: Logistik und Kundenservice_',
  adminTaxes: 'Shopify Admin: Settings > Taxes and duties',
  adminShipping: 'Shopify Admin: Settings > Shipping and delivery',

  secTax: 'Steuern und Zölle',
  subTaxService: 'Steuerdienst',
  lblTaxCalculation: 'Steuerberechnung',
  noteTaxService: '- Shopify Tax berechnet die USA, die EU, das Vereinigte Königreich und Kanada; andere Länder nutzen Sätze, die Sie bestätigen.',

  subRegistrations: 'Steuerliche Registrierungen',
  proseRegistrations: 'Eine Zeile je Land, Bundesstaat oder Verfahren, in dem Sie Steuern erheben. Verfahren für geringwertige Einfuhren gelten für die EU (IOSS), das Vereinigte Königreich, die Schweiz, Norwegen, Australien und Neuseeland',
  thRegistrations: ['Land, Bundesstaat oder Verfahren', 'Registriert?', 'Registrierungsnummer', 'Steuer erheben ab (Datum)', 'Anmerkungen'],
  rowEuCountries: 'EU-Länder (jede Registrierung einzeln auflisten)',
  cellLowValueScheme: 'Verfahren für geringwertige Einfuhren',

  subTaxDisplay: 'Preise und Steueranzeige je Markt',
  proseTaxDisplay: 'Preise können in manchen Märkten inklusive und in anderen exklusive Steuer angezeigt werden',
  proseTaxDisplayTail: 'nur Produktpreise, nicht Versandkosten',
  linkTaxDisplay: 'dynamische Steueranzeige',
  lblApproach: 'Vorgehen',
  thTaxDisplay: ['Markt', 'Währung', 'Preise inklusive Steuer?', 'Versandkosten inklusive Steuer?'],

  subDuties: 'Zölle und Einfuhrsteuern',
  proseDuties: 'Je Land werden Zölle entweder im Checkout erhoben (DDP) oder von der Kundschaft bei Zustellung bezahlt (DAP) — nicht beides. Zölle im Checkout zu erheben lässt sich nicht mit Steuerüberschreibungen, manuellen Steuersätzen oder Steuerbefreiungen von Kunden kombinieren, und manche Ziele werden nicht unterstützt',
  proseDutiesTail: 'Produkte brauchen HS-Codes und ein Ursprungsland.',
  lblHsCodes: 'HS-Codes und Ursprungsland',
  thDuties: ['Markt oder Land', 'DDP oder DAP', 'Carrier und Service für DDP-Sendungen', 'Anmerkungen'],

  subUsTax: 'US Sales Tax',
  proseUsTax: 'Tragen Sie jeden Bundesstaat ein, in dem Sie zur Erhebung der Sales Tax registriert sind',
  proseUsTaxTail: 'In einigen Bundesstaaten (z. B. Kalifornien, Colorado, Florida, Illinois, Louisiana, Maine, Maryland) wählen Sie außerdem, wie der Versand besteuert wird.',
  thUsTax: ['Bundesstaat', 'Sales-Tax-ID', 'Registriert seit (Datum)', 'Versand besteuert (wenn zutreffend / immer / nie)'],

  subReduced: 'Ermäßigte Sätze, Befreiungen und Überschreibungen',
  proseReduced: 'Shopify Tax nutzt Produktkategorien für ermäßigte Sätze und Befreiungen; Überschreibungen gelten je Land oder Bundesstaat für eine manuelle Kategorie',
  lblReducedProducts: 'Produkte mit ermäßigten Sätzen, Nullsätzen oder Befreiungen',
  thReduced: ['Produkte oder Kategorie', 'Land oder Bundesstaat', 'Satz oder Befreiung', 'Rechtsgrundlage (von Ihrer Beratung)'],

  subB2bTax: 'B2B-Steuern',
  proseB2bTax: 'Unternehmensstandorte können Steuernummern und Befreiungen hinterlegen. Die automatische Prüfung der EU-USt-IdNr. (Reverse Charge) setzt Shopify Tax, einen Fulfillment-Standort in der EU und das Checkout-Feld „Company VAT number“ voraus',
  lblTaxExempt: 'Steuerbefreite Geschäftskunden',
  thB2bTax: ['Kundentyp oder Unternehmen', 'Land', 'USt-IdNr. geprüft?', 'Befreit oder Reverse Charge?', 'Nachweis aufbewahrt'],

  subInvoices: 'Rechnungen',
  proseInvoices: 'Shopify kann MwSt.-Rechnungen für EU- und UK-Bestellungen erzeugen (sichtbar auf der Bestellstatusseite, nicht per E-Mail, nicht für Bestellungen mit Zöllen;',
  proseInvoicesTail: 'E-Invoicing (z. B. Peppol, XRechnung, SdI, KSeF) kommt aus Ihrem ERP oder einer Rechnungs-App.',
  lblInvoiceIssuer: 'Rechnungen ausgestellt von',
  lblEInvoicing: 'Pflichten zur elektronischen Rechnungsstellung',
  thInvoices: ['Juristische Person', 'Märkte', 'Format der Rechnungsnummer', 'E-Rechnungsstandard', 'Rechtstext auf Rechnungen'],

  secShipping: 'Versand und Zustellung',
  subLocations: 'Standorte',
  lblFulfilmentModel: 'Fulfillment-Modell',
  thLocations: ['Name des Standorts', 'Land', 'Beliefert Online-Bestellungen?', 'Abholung in der Filiale?', 'Lokale Lieferung?', 'Annahmeschluss für Bestellungen', 'Bearbeitungstage'],

  subZones: 'Versandzonen und Versandkosten',
  proseZones: 'Eine Zeile je Tarif, der im Checkout erscheint. Decken Sie jeden Gewichts- und Wertebereich ab: Eine Bestellung außerhalb aller Bereiche erhält im Checkout einen Versandfehler.',
  lblRates: 'Wie die Versandkosten berechnet werden',
  thZones: ['Markt', 'Länder in der Zone', 'Tarifname im Checkout', 'Service', 'Preis, oder vom Carrier berechnet', 'Bedingung (Gewicht oder Bestellwert)', 'Kostenlos ab', 'Angezeigte Lieferzeit'],

  subCarriers: 'Carrier und Labels',
  lblLabelSource: 'Labels erstellt in',
  thCarriers: ['Carrier', 'Genutzte Services', 'Märkte', 'Konto vorhanden?', 'Format des Tracking-Links'],

  subWeights: 'Produktgewichte und Pakete',
  proseWeights: 'Labels sowie gewichtsbasierte oder vom Carrier berechnete Tarife brauchen korrekte Produktgewichte und ein Standardpaket',
  lblWeightSource: 'Produktgewichte stammen aus',
  thPackages: ['Name des Pakets', 'Art (Karton, Versandtasche, Umschlag)', 'Maße', 'Leergewicht', 'Standard?'],

  subDeliveryDates: 'Liefertermine',
  proseDeliveryDates: 'Shopify kann automatische Liefertermine für Inlandsbestellungen in den USA und 32 europäischen Ländern anzeigen, wenn die Zustellung bis zu 5 Tage (USA) oder 4 Tage (Europa) dauert',
  thDeliveryDates: ['Markt', 'Liefertermine anzeigen?', 'Übliche Transporttage', 'Feiertage oder geschlossene Tage'],

  subLocalDelivery: 'Lokale Lieferung',
  proseLocalDelivery: 'Je Standort: ein Liefergebiet über Radius (bis 160 km) oder Postleitzahlen, bis zu 10 Zonen und 3 Preisregeln je Zone. Im B2B-Checkout nicht verfügbar',
  thLocalDelivery: ['Standort', 'Gebiet (Radius oder Postleitzahlen)', 'Preisregeln', 'Mindestbestellwert', 'Liefertage und -zeiten'],

  subPickup: 'Abholung',
  prosePickupA: 'Die Abholung in der Filiale wird je Standort eingestellt',
  prosePickupB: 'Paketshops sind nur für Stores in Frankreich, Italien, Spanien und dem Vereinigten Königreich mit bestimmten Carriern nativ; für B2B und Express-Wallets stehen sie nicht zur Verfügung',
  thPickup: ['Standort, Carrier oder App', 'Art (Filialabholung / Paketshop)', 'Märkte', 'Abholbereit in', 'Hinweise zur Abholung'],

  subSpecial: 'Besondere Produkte und Einschränkungen',
  proseSpecialA: 'Gefahrgut braucht ein eigenes Versandprofil und eigene Carrier-Vereinbarungen; für Einstufung und Kennzeichnung ist der Händler verantwortlich',
  proseSpecialB: 'Produkte, die in einem Markt nicht erlaubt sind, werden aus dem Katalog dieses Markts ausgeschlossen',
  lblDangerousGoods: 'Gefahrgut',
  lblSpecialRules: 'Produktspezifische Versandregeln',
  lblExcludedCountries: 'Länder, in die Sie nicht versenden',
  lblRestrictedProducts: 'Produkte, die in manchen Märkten eingeschränkt sind',
  thSpecial: ['Produkt oder Kategorie', 'Regel (Gefahrgut / im Markt nicht verkauft / Sondertarif)', 'Betroffene Märkte', 'Carrier oder Service', 'Anmerkungen'],

  subB2bShipping: 'B2B-Versand',
  proseB2bShipping: 'Geschäftskunden sehen dieselben Versandarten wie Endkunden, sofern Sie sie nicht anpassen; Bestellungen können als Entwurf eingereicht werden, damit der Versand vor der Zahlung kalkuliert wird',
  lblB2bRules: 'Regeln, die im B2B abweichen',
  thB2bShipping: ['Regel', 'Welche Einkäufer oder Unternehmensstandorte', 'Detail (Tarife, Schwellen, Carrier-Konto)'],

  subReturns: 'Retourenversand',
  lblReturnWindow: 'Retourenfrist (Tage)',
  lblReturnPaidBy: 'Wer trägt das Rücksendeporto',
  lblReturnLabel: 'Wie Artikel zurückgesendet werden',
  lblInternationalReturns: 'Internationale Retouren',
  thReturns: ['Markt', 'Retourenadresse oder Standort', 'Retourengebühr', 'Carrier oder Label'],

  secSignOff: 'Freigabe',
  proseSignOff: 'Nur Rollen — keine Namen oder Kontaktdaten in diesem Dokument.',
  thSignOff: ['Abschnitt', 'Bestätigt von (Rolle)', 'Datum'],

  cliDone: 'Konfigurationshandbuch für den Store (Steuern und Versand)',
  cliShare: 'Nach Vereinbarung des Umfangs mit dem Kunden teilen; Finanzen und Logistik füllen es vor der Store-Einrichtung aus.',
};

/** @type {Record<string, any>} */
const fr = {
  title: (client) => `Cahier de configuration de la boutique — ${client}`,
  intro: [
    "> **De quoi il s'agit :** les informations de fiscalité et de livraison dont nous avons besoin pour configurer votre",
    '> boutique Shopify. Vos équipes financières et logistiques le complètent une fois le périmètre convenu. Les valeurs',
    '> marquées *issu de la discovery* proviennent de nos séances de discovery — merci de les vérifier. Ne laissez aucun champ',
    '> vide : écrivez « sans objet » ou « à décider ». Les décisions fiscales et juridiques restent du ressort de votre équipe',
    '> financière et de vos conseils ; Merkle configure ce que vous confirmez.',
    '>',
    "> **N'inscrivez jamais de mots de passe, de clés d'API ni d'identifiants de compte transporteur dans ce document** — nous les recueillons par un canal sécurisé.",
  ],
  china: "_La Chine continentale n'est pas couverte par ce cahier : elle est traitée dans une discovery Chine distincte._",
  help: 'aide Shopify',
  fromDiscovery: '*(issu de la discovery)*',
  fromDiscoveryConfirm: '*(issu de la discovery — à confirmer)*',
  toComplete: '_à compléter_',
  yes: 'Oui',
  no: 'Non',
  ownerFinance: '_Responsable : finance_',
  ownerLogistics: '_Responsable : logistique et service client_',
  adminTaxes: 'Interface Shopify : Settings > Taxes and duties',
  adminShipping: 'Interface Shopify : Settings > Shipping and delivery',

  secTax: 'Fiscalité et droits de douane',
  subTaxService: 'Service fiscal',
  lblTaxCalculation: 'Calcul de la taxe',
  noteTaxService: '- Shopify Tax calcule les États-Unis, l\'UE, le Royaume-Uni et le Canada ; les autres pays utilisent des taux que vous confirmez.',

  subRegistrations: 'Immatriculations fiscales',
  proseRegistrations: "Une ligne par pays, État ou régime où vous collectez la taxe. Les régimes d'importation de faible valeur s'appliquent à l'UE (IOSS), au Royaume-Uni, à la Suisse, à la Norvège, à l'Australie et à la Nouvelle-Zélande",
  thRegistrations: ['Pays, État ou régime', 'Immatriculé ?', "Numéro d'immatriculation", 'Collecte de la taxe à partir du (date)', 'Remarques'],
  rowEuCountries: "Pays de l'UE (lister chaque immatriculation)",
  cellLowValueScheme: "Régime d'importation de faible valeur",

  subTaxDisplay: 'Prix et affichage de la taxe par marché',
  proseTaxDisplay: "Les prix peuvent inclure la taxe sur certains marchés et l'exclure sur d'autres",
  proseTaxDisplayTail: 'prix des produits uniquement, pas les frais de port',
  linkTaxDisplay: 'affichage fiscal dynamique',
  lblApproach: 'Approche',
  thTaxDisplay: ['Marché', 'Devise', 'Prix taxe incluse ?', 'Frais de port taxe incluse ?'],

  subDuties: 'Droits de douane et taxes à l\'importation',
  proseDuties: "Par pays, les droits sont soit perçus au paiement (DDP), soit payés par le client à la livraison (DAP) — pas les deux. Percevoir les droits au paiement ne se combine pas avec les surcharges fiscales, les taux manuels ni les exonérations client, et certaines destinations ne sont pas prises en charge",
  proseDutiesTail: "Les produits ont besoin de codes SH et d'un pays d'origine.",
  lblHsCodes: "Codes SH et pays d'origine",
  thDuties: ['Marché ou pays', 'DDP ou DAP', 'Transporteur et service pour les envois DDP', 'Remarques'],

  subUsTax: 'Taxe de vente américaine',
  proseUsTax: 'Ajoutez chaque État où vous êtes immatriculé pour collecter la taxe de vente',
  proseUsTaxTail: "Dans certains États (par exemple Californie, Colorado, Floride, Illinois, Louisiane, Maine, Maryland), vous choisissez aussi comment la livraison est taxée.",
  thUsTax: ['État', 'Identifiant de taxe de vente', 'Immatriculé depuis (date)', 'Livraison taxée (selon le cas / toujours / jamais)'],

  subReduced: 'Taux réduits, exonérations et surcharges',
  proseReduced: 'Shopify Tax utilise les catégories de produits pour les taux réduits et les exonérations ; les surcharges s\'appliquent par pays ou par État à une collection manuelle',
  lblReducedProducts: 'Produits à taux réduit, à taux zéro ou exonérés',
  thReduced: ['Produits ou collection', 'Pays ou État', 'Taux ou exonération', 'Base juridique (de votre conseil)'],

  subB2bTax: 'Fiscalité B2B',
  proseB2bTax: "Les emplacements d'entreprise peuvent porter des numéros d'immatriculation fiscale et des exonérations. La validation automatique du numéro de TVA européen (autoliquidation) exige Shopify Tax, un emplacement de préparation dans l'UE et le champ de paiement « Company VAT number »",
  lblTaxExempt: 'Acheteurs professionnels exonérés',
  thB2bTax: ["Type d'acheteur ou entreprise", 'Pays', 'Numéro de TVA validé ?', 'Exonéré ou autoliquidation ?', 'Preuve conservée'],

  subInvoices: 'Factures',
  proseInvoices: "Shopify peut générer des factures de TVA pour les commandes de l'UE et du Royaume-Uni (affichées sur la page de statut de commande, non envoyées par e-mail, pas pour les commandes avec droits ;",
  proseInvoicesTail: "La facturation électronique (par exemple Peppol, XRechnung, SdI, KSeF) vient de votre ERP ou d'une application de facturation.",
  lblInvoiceIssuer: 'Factures émises par',
  lblEInvoicing: 'Obligations de facturation électronique',
  thInvoices: ['Entité juridique', 'Marchés', 'Format du numéro de facture', 'Norme de facturation électronique', 'Mentions légales sur les factures'],

  secShipping: 'Livraison et expédition',
  subLocations: 'Emplacements',
  lblFulfilmentModel: 'Modèle de préparation des commandes',
  thLocations: ["Nom de l'emplacement", 'Pays', 'Prépare les commandes en ligne ?', 'Retrait en magasin ?', 'Livraison locale ?', 'Heure limite de commande', 'Jours de traitement'],

  subZones: 'Zones et tarifs de livraison',
  proseZones: "Une ligne par tarif affiché au paiement. Couvrez chaque plage de poids ou de montant : une commande hors de toutes les plages reçoit une erreur de livraison au paiement.",
  lblRates: 'Mode de calcul des tarifs',
  thZones: ['Marché', 'Pays de la zone', 'Nom du tarif au paiement', 'Service', 'Prix, ou calculé par le transporteur', 'Condition (poids ou montant)', 'Offert au-delà de', 'Délai affiché'],

  subCarriers: 'Transporteurs et étiquettes',
  lblLabelSource: 'Étiquettes créées dans',
  thCarriers: ['Transporteur', 'Services utilisés', 'Marchés', 'Compte en place ?', 'Format du lien de suivi'],

  subWeights: 'Poids des produits et colis',
  proseWeights: 'Les étiquettes et les tarifs au poids ou calculés par le transporteur exigent des poids de produits exacts et un colis par défaut',
  lblWeightSource: 'Les poids des produits proviennent de',
  thPackages: ['Nom du colis', 'Type (carton, pochette, enveloppe)', 'Dimensions', 'Poids à vide', 'Par défaut ?'],

  subDeliveryDates: 'Dates de livraison',
  proseDeliveryDates: "Shopify peut afficher des dates de livraison automatiques pour les commandes domestiques aux États-Unis et dans 32 pays européens lorsque la livraison prend jusqu'à 5 jours (États-Unis) ou 4 jours (Europe)",
  thDeliveryDates: ['Marché', 'Afficher les dates de livraison ?', 'Jours de transit habituels', 'Jours fériés ou de fermeture'],

  subLocalDelivery: 'Livraison locale',
  proseLocalDelivery: "Par emplacement : une zone de livraison par rayon (jusqu'à 160 km) ou par codes postaux, jusqu'à 10 zones et 3 règles de prix par zone. Non proposée au paiement B2B",
  thLocalDelivery: ['Emplacement', 'Zone (rayon ou codes postaux)', 'Règles de prix', 'Commande minimum', 'Jours et horaires de livraison'],

  subPickup: 'Retrait',
  prosePickupA: 'Le retrait en magasin se règle par emplacement',
  prosePickupB: "Les points relais ne sont natifs que pour les boutiques en France, en Italie, en Espagne et au Royaume-Uni avec certains transporteurs ; ils ne sont disponibles ni pour le B2B ni pour les portefeuilles express",
  thPickup: ['Emplacement, transporteur ou application', 'Type (retrait en magasin / point relais)', 'Marchés', 'Prêt pour le retrait sous', 'Consignes de retrait'],

  subSpecial: 'Produits particuliers et restrictions',
  proseSpecialA: "Les marchandises dangereuses exigent leur propre profil de livraison et des accords transporteurs dédiés ; le marchand est responsable de la classification et de l'étiquetage",
  proseSpecialB: "Les produits non autorisés sur un marché sont exclus du catalogue de ce marché",
  lblDangerousGoods: 'Marchandises dangereuses',
  lblSpecialRules: "Règles d'expédition propres à certains produits",
  lblExcludedCountries: "Pays vers lesquels vous n'expédiez pas",
  lblRestrictedProducts: 'Produits restreints sur certains marchés',
  thSpecial: ['Produit ou collection', 'Règle (marchandises dangereuses / non vendu sur le marché / tarif particulier)', 'Marchés concernés', 'Transporteur ou service', 'Remarques'],

  subB2bShipping: 'Livraison B2B',
  proseB2bShipping: "Les acheteurs professionnels voient les mêmes modes de livraison que les particuliers, sauf personnalisation ; les commandes peuvent être soumises en provisoire pour chiffrer la livraison avant le paiement",
  lblB2bRules: 'Règles différentes en B2B',
  thB2bShipping: ['Règle', "Quels acheteurs ou emplacements d'entreprise", 'Détail (tarifs, seuils, compte transporteur)'],

  subReturns: 'Retours',
  lblReturnWindow: 'Délai de retour (jours)',
  lblReturnPaidBy: 'Qui paie le retour',
  lblReturnLabel: 'Comment les articles sont renvoyés',
  lblInternationalReturns: 'Retours internationaux',
  thReturns: ['Marché', 'Adresse ou emplacement de retour', 'Frais de retour', 'Transporteur ou étiquette'],

  secSignOff: 'Validation',
  proseSignOff: 'Rôles uniquement — aucun nom ni coordonnée dans ce document.',
  thSignOff: ['Section', 'Validé par (rôle)', 'Date'],

  cliDone: 'cahier de configuration de la boutique (fiscalité et livraison)',
  cliShare: 'À partager avec le client une fois le périmètre convenu ; finance et logistique le complètent avant la configuration de la boutique.',
};

const CATALOGUES = { en, de, fr };

/**
 * The workbook's words in one language. English is the source, and is what an
 * engagement with no language recorded gets.
 *
 * @param {string} [language]
 * @returns {typeof en}
 */
export function words(language) {
  if (isEnglish(language)) return en;
  return CATALOGUES[String(language).toLowerCase()] ?? en;
}

export const WORKBOOK_LANGUAGES = Object.keys(CATALOGUES);
