/**
 * @file catalogue.js — epic "Catalogue & product data" (LWC-CAT-*)
 */

import { hasProductType, isMigration, listOr, count, integrationsOf } from './helpers.js';

const attributes = (doc) => doc.catalogue?.custom_attributes ?? [];
const namespace = (doc) => `client_${(doc.meta?.client?.slug ?? 'store').split('-')[0].replace(/[^a-z0-9]/g, '')}`;
const oosBehaviour = {
  hide: 'hide sold-out products from collections and search',
  show_sold_out: 'show sold-out products with a disabled, clearly labelled button',
  backorder: 'continue selling when out of stock with a clear back-order message and dispatch estimate',
  notify_me: 'show sold-out products with a back-in-stock sign-up instead of the add to cart button',
};

/** @type {import('../model.js').StoryDefinition[]} */
export default [
  {
    key: 'LWC-CAT-001',
    epic: 'catalogue',
    title: 'Define the product model, variant options and inventory behaviour',
    user_story: 'As a merchandiser, I want a consistent product structure with clear variant options and stock rules, so that products are easy to manage and shoppers always see accurate availability.',
    description: (doc) => `About ${count(doc.catalogue?.sku_count, 'an unconfirmed number of')} SKUs, up to ${doc.catalogue?.variant_options_max ?? 'an unconfirmed number of'} options and ${doc.catalogue?.variants_per_product_max ?? 'an unconfirmed number of'} variants per product. Product types: ${listOr(doc.catalogue?.product_types, 'to confirm')}.`,
    acceptance_criteria: (doc) => [
      `Given the product model document, when it is reviewed, then every product uses at most 3 options (engagement maximum ${doc.catalogue?.variant_options_max ?? 'to confirm'}) with consistent option names and values across the catalogue`,
      'Given the Shopify Standard Product Taxonomy, when products are categorised, then each product has a category so that category metafields, tax and marketplace mappings are available',
      `Given a variant runs out of stock, when a shopper views it, then the store will ${oosBehaviour[doc.catalogue?.inventory?.out_of_stock_behaviour] ?? 'follow the agreed out-of-stock rule'}`,
      ...(doc.catalogue?.inventory?.low_stock_alerts ? ['Given a variant falls below its threshold, when inventory changes, then a Shopify Flow workflow notifies the responsible team'] : []),
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'agent',
    depends_on: ['LWC-FND-001'],
    spec_refs: ['/catalogue/sku_count', '/catalogue/variant_options_max', '/catalogue/variants_per_product_max', '/catalogue/product_types', '/catalogue/inventory/out_of_stock_behaviour', '/catalogue/inventory/low_stock_alerts', '/catalogue/inventory/source'],
    gates: ['sku_complexity'],
    applies: () => true,
    agent_prompt: (doc) => `Draft the product model for about ${count(doc.catalogue?.sku_count, 'the agreed number of')} SKUs: product vs variant boundaries, option names and value lists (maximum 3 options; engagement maximum ${doc.catalogue?.variant_options_max ?? 'to confirm'}; up to ${doc.catalogue?.variants_per_product_max ?? 'to confirm'} variants per product), SKU and barcode conventions, Standard Product Taxonomy category per product type, vendor and product type values, and tags policy (tags for operations only, not for data that belongs in metafields). Where a model is sold in several colours that should appear as separate product pages, propose Combined Listings (Plus). Inventory source of truth: ${doc.catalogue?.inventory?.source ?? 'to confirm'}; track inventory on all physical variants; out-of-stock rule: ${oosBehaviour[doc.catalogue?.inventory?.out_of_stock_behaviour] ?? 'to confirm'}.${doc.catalogue?.inventory?.low_stock_alerts ? ' Create a Shopify Flow low-stock alert workflow.' : ''} Present the model for consultant approval before creating any product.`,
  },
  {
    key: 'LWC-CAT-002',
    epic: 'catalogue',
    title: (doc) => `Create metafield definitions and filters for ${attributes(doc).length} product attribute${attributes(doc).length === 1 ? '' : 's'}`,
    description: (doc) => `Attributes: ${listOr(attributes(doc), 'to confirm')}.`,
    user_story: 'As a shopper, I want to see and filter by the product attributes that matter to me, so that I can compare products quickly.',
    acceptance_criteria: (doc) => [
      ...attributes(doc).map((a) => `Given the attribute ${a}, when its definition is created, then it has a typed metafield definition (or maps to a standard category metafield) with validation and is pinned in the product admin`),
      'Given the definitions, when they are enabled for storefront access, then they are available as dynamic sources in the theme editor',
      'Given the Search & Discovery app, when filters are configured, then each filterable attribute appears as a collection and search filter with translated labels',
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'agent',
    depends_on: ['LWC-CAT-001'],
    spec_refs: ['/catalogue/custom_attributes', '/catalogue/data_source'],
    gates: ['sku_complexity'],
    applies: (doc) => attributes(doc).length > 0,
    agent_prompt: (doc) => `For each attribute in ${listOr(attributes(doc), 'engagement.catalogue.custom_attributes')}: first check whether a Standard Product Taxonomy category metafield already covers it and use that where it does. Otherwise create a product metafield definition with metafieldDefinitionCreate in namespace ${namespace(doc)}, a snake_case key and the narrowest type (number_integer or number_decimal for measurements, single_line_text_field with choices validation for enumerations, metaobject_reference for values that need labels, images or translations, list types for multi-value). Enable storefront access and pin the definitions. Then add filters for the filterable attributes in the Shopify Search & Discovery app. Data source: ${doc.catalogue?.data_source ?? 'to confirm'} — document the field mapping for the import or integration. Present the definitions for approval before creating them.`,
  },
  {
    key: 'LWC-CAT-003',
    epic: 'catalogue',
    title: (doc) => `Set up the collection structure (${{ manual: 'manual', automated: 'automated', mixed: 'automated and manual' }[doc.catalogue?.collection_mode] ?? 'automated and manual'} collections)`,
    user_story: 'As a merchandiser, I want collections that stay up to date by rules where possible, so that merchandising takes minutes not hours.',
    acceptance_criteria: (doc) => [
      `Given the collection plan of about ${doc.catalogue?.collections_estimate ?? 'the agreed number of'} collections, when collections are created, then rule-based collections use product type, vendor, tag or metafield conditions and manual collections are limited to curated edits`,
      'Given a new product that matches a rule, when it is published, then it appears in the right automated collections without manual work',
      'Given each collection, when it is reviewed, then it has an SEO title, meta description, image and a sort order agreed with merchandising',
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'agent',
    depends_on: ['LWC-CAT-001'],
    spec_refs: ['/catalogue/collections_estimate', '/catalogue/collection_mode'],
    applies: () => true,
    agent_prompt: (doc) => `Propose the collection tree (about ${doc.catalogue?.collections_estimate ?? 'the agreed number of'} collections, mode ${doc.catalogue?.collection_mode ?? 'to confirm'}) mapped to the main menu. Prefer automated collections with conditions on product type, vendor, category, tag or metafield; use manual collections only for curated edits. Set sort order, SEO title and description, and collection image. Present the tree for approval, then create collections with the Admin API or bulk import.`,
  },
  {
    key: 'LWC-CAT-004',
    epic: 'catalogue',
    title: 'Set up product bundles with Shopify Bundles',
    user_story: 'As a shopper, I want to buy curated bundles in one click, so that I get complementary products at a clear price.',
    acceptance_criteria: [
      'Given a fixed bundle, when it is created in the Shopify Bundles app, then its component variants are linked and inventory is deducted from the components on purchase',
      'Given a bundle in the cart and checkout, when an order is placed, then the order shows the bundle and its components for fulfilment',
      'Given a component goes out of stock, when a shopper views the bundle, then the bundle shows as unavailable',
    ],
    gaia_tier: 'T2',
    points: 5,
    owner: 'agent',
    depends_on: ['LWC-CAT-001'],
    spec_refs: ['/catalogue/product_types'],
    gates: ['sku_complexity'],
    applies: (doc) => hasProductType(doc, 'bundle'),
    agent_prompt: (doc) => `Install the Shopify Bundles app and create the fixed bundles and multipacks listed by merchandising. Use component variants so inventory is tracked on components. If a mix-and-match bundle is required that Shopify Bundles cannot model, stop and flag it: it needs a Cart Transform function (T3).${integrationsOf(doc, 'erp').length || integrationsOf(doc, '3pl_wms').length ? ' Confirm with the ERP/3PL owner how bundle orders and components are exported.' : ''} Verify the bundle price, the component breakdown on the order and the sold-out state.`,
  },
  {
    key: 'LWC-CAT-005',
    epic: 'catalogue',
    title: 'Model product sets and shop-the-look with metaobjects',
    user_story: 'As a shopper, I want to see products that belong together and add them easily, so that I can buy a complete set.',
    acceptance_criteria: [
      'Given a product set metaobject definition, when a merchandiser creates an entry, then it references its products and has a title, image and description that can be translated',
      'Given a product page or landing page, when a product set block is added in the theme editor, then it lists the referenced products with variant selection and add to cart',
      'Given a referenced product is archived, when the set renders, then the product is skipped without breaking the block',
    ],
    gaia_tier: 'T3',
    points: 5,
    owner: 'developer',
    depends_on: ['LWC-CAT-001', 'LWC-THM-001'],
    spec_refs: ['/catalogue/product_types'],
    gates: ['sku_complexity'],
    applies: (doc) => hasProductType(doc, 'product_set'),
    agent_prompt: (doc) => `Create a metaobject definition product_set (namespace ${namespace(doc)} conventions; fields title, description, image, products as list.product_reference) with storefront access and the translations capability. Add a product.metafield list.metaobject_reference linking products to their sets. Build a theme block that renders the set with variant pickers and adds selected items to cart via the Cart AJAX API. Present the definition for approval before creating it.`,
  },
  {
    key: 'LWC-CAT-006',
    epic: 'catalogue',
    title: (doc) => `Set up subscription products with ${doc.catalogue?.subscription_app ?? 'Shopify Subscriptions'}`,
    user_story: 'As a regular customer, I want to subscribe to products at a discount, so that I never run out.',
    acceptance_criteria: [
      'Given a subscription product, when a shopper selects a delivery frequency, then the selling plan price and frequency are shown on the product page and in the cart',
      'Given a subscription order, when it is placed, then a subscription contract is created and the next billing attempt succeeds in test mode',
      'Given a subscriber, when they log in to customer accounts, then they can pause, skip or cancel according to the agreed policy',
    ],
    gaia_tier: 'T3',
    points: 5,
    owner: 'agent',
    depends_on: ['LWC-CAT-001', 'LWC-PAY-001'],
    spec_refs: ['/catalogue/product_types', '/catalogue/subscription_app'],
    security_flags: ['payments', 'pii'],
    applies: (doc) => hasProductType(doc, 'subscription'),
    agent_prompt: (doc) => `Install ${doc.catalogue?.subscription_app ?? 'Shopify Subscriptions'} and create selling plan groups (frequencies, discount) for the subscription products. Add the app's subscription block to the product template in the theme editor. Confirm the payment providers support vaulted payments for subscriptions (Shopify Payments or supported gateways). Configure customer self-service in customer accounts and the dunning rules. Test create, renew, skip and cancel in test mode.`,
  },
  {
    key: 'LWC-CAT-007',
    epic: 'catalogue',
    title: 'Enable pre-orders and made-to-order lead times',
    user_story: 'As a shopper, I want to order products before they are in stock or made for me, with a clear dispatch date, so that I know when to expect them.',
    acceptance_criteria: (doc) => [
      ...(hasProductType(doc, 'pre_order') ? ['Given a pre-order product, when it is viewed, then the button reads Pre-order and the expected dispatch date comes from a metafield or the selling plan'] : []),
      ...(hasProductType(doc, 'made_to_order') ? ['Given a made-to-order product, when it is viewed and ordered, then the production lead time is shown on the product page, in the cart and in the order confirmation'] : []),
      'Given a mixed cart of in-stock and pre-order items, when the shopper checks out, then the dispatch timing is clear and the order is tagged for fulfilment',
      'Given a pre-order paid later, when the payment is captured, then it follows the selling plan (deposit or full payment) agreed with finance',
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'agent',
    depends_on: ['LWC-CAT-001', 'LWC-PAY-001'],
    spec_refs: ['/catalogue/product_types', '/catalogue/inventory/out_of_stock_behaviour'],
    security_flags: ['payments'],
    applies: (doc) => hasProductType(doc, 'pre_order') || hasProductType(doc, 'made_to_order'),
    agent_prompt: (doc) => `Configure ${[hasProductType(doc, 'pre_order') ? 'pre-orders' : '', hasProductType(doc, 'made_to_order') ? 'made-to-order lead times' : ''].filter(Boolean).join(' and ')}. For pre-orders use an app built on Shopify pre-order selling plans (full payment or deposit with deferred capture) rather than overselling tricks; shortlist one app with cost for approval. Store dispatch dates or lead times in a typed product metafield and show them on the product page, cart and notifications. Tag orders for fulfilment. Test payment capture timing in test mode.`,
  },
  {
    key: 'LWC-CAT-008',
    epic: 'catalogue',
    title: 'Set up digital and non-shipping products',
    user_story: 'As a shopper buying a digital or virtual item, I want instant access and no shipping step, so that the purchase is quick.',
    acceptance_criteria: [
      'Given a digital or virtual product, when it is configured, then "This is a physical product" is off so checkout skips shipping for carts with only such items',
      'Given a digital download order, when payment succeeds, then the customer receives a secure download link by email and in the order status page',
      'Given a mixed cart with physical items, when the shopper checks out, then shipping is charged only for physical items',
    ],
    gaia_tier: 'T1',
    points: 2,
    owner: 'agent',
    depends_on: ['LWC-CAT-001'],
    spec_refs: ['/catalogue/product_types'],
    applies: (doc) => hasProductType(doc, 'digital') || hasProductType(doc, 'virtual'),
    agent_prompt: (doc) => `Mark ${[hasProductType(doc, 'digital') ? 'digital' : '', hasProductType(doc, 'virtual') ? 'virtual (service)' : ''].filter(Boolean).join(' and ')} products as not requiring shipping. ${hasProductType(doc, 'digital') ? 'Install the Shopify Digital Downloads app (or a shortlisted alternative if licence keys or streaming are needed), attach files to the digital variants and set download limits.' : ''} Hide delivery estimates on these product pages. Test mixed and digital-only carts.`,
  },
  {
    key: 'LWC-CAT-009',
    epic: 'catalogue',
    title: 'Add back-in-stock notifications through an app',
    user_story: 'As a shopper, I want to be emailed when a sold-out variant is back, so that I do not miss it.',
    description: 'Shopify has no built-in back-in-stock notifications; this needs an app or the ESP\'s back-in-stock feature.',
    acceptance_criteria: (doc) => [
      'Given a sold-out variant, when a shopper opens the product page, then a notify-me form replaces the add to cart button for that variant only',
      `Given a sign-up, when the variant is restocked, then an email is sent in the shopper's language${doc.marketing?.esp?.platform ? ` from ${doc.marketing.esp.platform}` : ''} with a link to the variant`,
      'Given the sign-up form, when a shopper submits it, then marketing consent is not assumed and the request is used only for the stock alert unless they opt in',
    ],
    gaia_tier: 'T2',
    points: 2,
    owner: 'agent',
    depends_on: ['LWC-THM-005'],
    spec_refs: ['/catalogue/inventory/out_of_stock_behaviour', '/marketing/esp/platform'],
    security_flags: ['pii'],
    applies: (doc) => doc.catalogue?.inventory?.out_of_stock_behaviour === 'notify_me',
    agent_prompt: (doc) => `Shopify does not send back-in-stock notifications natively. ${doc.marketing?.esp?.platform ? `First check whether ${doc.marketing.esp.platform} offers back-in-stock flows (it avoids another app); otherwise shortlist` : 'Shortlist'} one back-in-stock app with cost and multilingual support for approval. Add the app block to the product template (variant-aware), build the notification template in every storefront language and keep the stock-alert request separate from marketing consent. Test with a variant set to zero then restocked.`,
  },
  {
    key: 'LWC-CAT-010',
    epic: 'catalogue',
    title: (doc) => `Import the initial catalogue from ${doc.catalogue?.data_source === 'shopify_admin' ? 'the Shopify admin template' : 'the client spreadsheet'}`,
    user_story: 'As a merchandiser, I want the launch catalogue loaded completely and correctly, so that we can review real products before launch.',
    acceptance_criteria: (doc) => [
      `Given the client product file, when it is validated against the product model, then every row has title, handle, SKU, price, options, category and required metafields${attributes(doc).length ? ` (${listOr(attributes(doc), '')})` : ''} or is listed in an error report`,
      `Given the import, when it completes, then about ${count(doc.catalogue?.sku_count, 'all')} SKUs exist with images, alt text and inventory, and a spot check of 20 products matches the source`,
      'Given the import is repeated, when the same file is loaded again, then products are updated by handle and no duplicates are created',
    ],
    gaia_tier: 'T2',
    points: 3,
    owner: 'agent',
    depends_on: ['LWC-CAT-001', 'LWC-CAT-002'],
    spec_refs: ['/catalogue/data_source', '/catalogue/sku_count', '/catalogue/custom_attributes'],
    applies: (doc) => !isMigration(doc) && !['erp', 'pim'].includes(doc.catalogue?.data_source),
    agent_prompt: (doc) => `Provide the client with an import template matching the approved product model (Shopify product CSV columns plus metafield columns${attributes(doc).length ? ` for ${listOr(attributes(doc), '')}` : ''}). Validate the returned file (required fields, option consistency, prices, image URLs, handle uniqueness) and send an error report. Import with the Shopify product CSV importer or Matrixify for metafields, updating by handle so re-runs are idempotent. Spot-check 20 products and report counts.`,
  },
];
